Repository wulkanowy/wulkanowy, pull requests merged in 2018-11, with the labels that each got.

#171 Timetable widget refactor
  .idea/codeStyles/Project.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/data/db/SharedPrefHelper.kt
  app/src/main/java/io/github/wulkanowy/di/BuilderModule.kt
  app/src/main/java/io/github/wulkanowy/services/notification/GradeNotification.kt
  app/src/main/java/io/github/wulkanowy/services/widgets/TimetableWidgetService.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/widgets/timetable/TimetableWidgetFactory.kt
  app/src/main/java/io/github/wulkanowy/ui/widgets/timetable/TimetableWidgetProvider.kt
  app/src/main/res/drawable/ic_widget_chevron_24dp.png
  app/src/main/res/drawable/img_timetable_widget_preview.png
  app/src/main/res/drawable/img_timetable_widget_preview.webp
  app/src/main/res/layout/item_widget_timetable.xml
  app/src/main/res/layout/widget_timetable.xml
  app/src/main/res/xml/provider_widget_timetable.xml
Labels: app, hacktoberfest, ui

#178 Add preference for the expandable grades
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/services/job/ServiceHelper.kt
  app/src/main/java/io/github/wulkanowy/services/job/SyncWorker.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsHeader.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences.xml
Labels: app, ux

#179 Add notes
  .gitignore
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/NoteDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Note.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/NoteRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/local/NoteLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/remote/NoteRemote.kt
  app/src/main/java/io/github/wulkanowy/services/job/SyncWorker.kt
  app/src/main/java/io/github/wulkanowy/services/notification/NoteNotification.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainModule.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MorePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NotePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteView.kt
  app/src/main/res/drawable-hdpi/ic_stat_notify_note.png
  app/src/main/res/drawable-mdpi/ic_stat_notify_note.png
  app/src/main/res/drawable-xhdpi/ic_stat_notify_note.png
  app/src/main/res/drawable-xxhdpi/ic_stat_notify_note.png
  app/src/main/res/drawable-xxxhdpi/ic_stat_notify_note.png
  app/src/main/res/drawable/ic_menu_main_note_24dp.xml
  app/src/main/res/drawable/ic_menu_main_timetable_24dp.xml
  app/src/main/res/layout/dialog_note.xml
  app/src/main/res/layout/fragment_note.xml
  app/src/main/res/layout/item_note.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: app, db, ui

#184 Fix no expandable grades
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsView.kt
Labels: app, fix

#185 Add config for travis ci
  .circleci/config.yml
  .gitignore
  .travis.yml
  README.md
  app/build.gradle
  app/sonarqube.gradle
  app/src/main/play/pl-PL/whatsnew
  build.gradle
Labels: ci

#186 Add details to error message
  app/src/main/java/io/github/wulkanowy/data/ErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BasePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseView.kt
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/options/LoginOptionsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/res/layout/dialog_error.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: new feature, ui

#187 Fix login when an error occurs
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/StudentLocalTest.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/AttendanceDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/ExamDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/GradeDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/GradeSummaryDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/HomeworkDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/NoteDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/SemesterDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/TimetableDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/local/SemesterLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/local/StudentLocal.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/options/LoginOptionsPresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/security/Scrambler.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/options/LoginOptionsPresenterTest.kt
Labels: db, fix

#188 Add version text to login form
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/layout/item_widget_timetable.xml
  app/src/main/res/values/colors.xml
Labels: ui

#190 Fix the deformed settings icon
  app/src/main/res/drawable/ic_account_add_24dp.xml
  app/src/main/res/drawable/ic_all_account_24dp.xml
  app/src/main/res/drawable/ic_menu_grade_semester_24dp.xml
  app/src/main/res/drawable/ic_menu_main_attendance_24dp.xml
  app/src/main/res/drawable/ic_menu_main_homework_24dp.xml
  app/src/main/res/drawable/ic_menu_main_note_24dp.xml
  app/src/main/res/drawable/ic_menu_main_timetable_24dp.xml
  app/src/main/res/drawable/ic_more_about_24dp.xml
  app/src/main/res/drawable/ic_more_settings_24dp.xml
Labels: fix, ui
