Repository wulkanowy/wulkanowy, pull requests merged in 2018-10, with the labels that each got.

#165 Refactor multi logs support
  app/build.gradle
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/SessionLocalTest.kt
  app/src/main/java/io/github/wulkanowy/data/ErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Student.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SessionRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/remote/SessionRemote.kt
  app/src/main/java/io/github/wulkanowy/ui/login/LoginErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/login/form/LoginFormView.kt
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/api_endpoints.xml
  app/src/main/res/values/api_symbols.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/data/repositories/remote/SessionRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/ui/login/form/LoginFormPresenterTest.kt
  app/src/test/java/io/github/wulkanowy/ui/login/options/LoginOptionsPresenterTest.kt
  build.gradle
Labels: app, db, hacktoberfest, ui, ux

#167 Change all entities ids from string to int
  app/build.gradle
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/AttendanceLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/ExamLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/SessionLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/TimetableLocalTest.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/AttendanceDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/ExamDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/GradeDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/GradeSummaryDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/SemesterDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/TimetableDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Attendance.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Exam.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Grade.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/GradeSummary.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Semester.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Student.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Timetable.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/remote/GradeRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/remote/GradeSummaryRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/remote/SessionRemote.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/GradeFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/GradePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/GradeView.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/details/GradeDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/details/GradeDetailsView.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/summary/GradeSummaryFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/summary/GradeSummaryPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/summary/GradeSummaryView.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/remote/AttendanceRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/remote/ExamRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/remote/SessionRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/remote/TimetableRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/utils/GradeExtensionTest.kt
Labels: api, hacktoberfest

#169 Migrate to AndroidX
  app/build.gradle
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/AttendanceLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/ExamLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/SessionLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/TimetableLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/utils/security/ScramblerTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/Converters.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/AttendanceDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/ExamDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/GradeDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/GradeSummaryDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/SemesterDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/TimetableDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Attendance.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Exam.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Grade.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/GradeSummary.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Semester.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Student.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Timetable.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BasePagerAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/login/options/LoginOptionsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/main/attendance/AttendanceDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/main/exam/ExamDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/main/exam/ExamItem.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/GradeFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/details/GradeDetailsDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/main/timetable/TimetableDialog.kt
  app/src/main/java/io/github/wulkanowy/utils/FragNavControlerExtension.kt
  app/src/main/java/io/github/wulkanowy/utils/ViewPagerExtension.kt
  app/src/main/res/drawable/img_splash_logo.png
  app/src/main/res/drawable/layer_splash_background.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_attendance.xml
  app/src/main/res/layout/fragment_exam.xml
  app/src/main/res/layout/fragment_grade.xml
  app/src/main/res/layout/fragment_grade_details.xml
  app/src/main/res/layout/fragment_grade_summary.xml
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/layout/fragment_login_options.xml
  app/src/main/res/layout/fragment_timetable.xml
  app/src/main/res/layout/header_exam.xml
  app/src/main/res/layout/header_grade_summary.xml
  app/src/main/res/layout/item_login_options.xml
  app/src/main/res/layout/widget_timetable.xml
  app/src/main/res/values/api_symbols.xml
  app/src/test/java/io/github/wulkanowy/ui/login/form/LoginFormPresenterTest.kt
  app/src/test/java/io/github/wulkanowy/ui/login/options/LoginOptionsPresenterTest.kt
  gradle.properties
Labels: app, hacktoberfest

#166 Settings refactor
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/login/LoginActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/login/LoginPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/login/LoginView.kt
  app/src/main/java/io/github/wulkanowy/ui/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/main/MainModule.kt
  app/src/main/java/io/github/wulkanowy/ui/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/main/MainView.kt
  app/src/main/java/io/github/wulkanowy/ui/main/about/AboutFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/main/about/AboutModule.kt
  app/src/main/java/io/github/wulkanowy/ui/main/about/AboutPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/main/about/AboutView.kt
  app/src/main/java/io/github/wulkanowy/ui/main/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/main/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/main/attendance/AttendanceView.kt
  app/src/main/java/io/github/wulkanowy/ui/main/exam/ExamFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/main/exam/ExamPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/main/exam/ExamView.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/GradeFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/GradePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/GradeView.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/details/GradeDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/details/GradeDetailsView.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/summary/GradeSummaryFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/summary/GradeSummaryPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/main/grade/summary/GradeSummaryView.kt
  app/src/main/java/io/github/wulkanowy/ui/main/more/MoreFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/main/more/MoreItem.kt
  app/src/main/java/io/github/wulkanowy/ui/main/more/MorePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/main/more/MoreView.kt
  app/src/main/java/io/github/wulkanowy/ui/main/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/main/timetable/TimetableFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/main/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/main/timetable/TimetableView.kt
  app/src/main/java/io/github/wulkanowy/utils/FragNavControlerExtension.kt
  app/src/main/java/io/github/wulkanowy/utils/LibsBuiderExtension.kt
  app/src/main/res/drawable/ic_more_about_24dp.xml
  app/src/main/res/drawable/ic_more_settings_24dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_more.xml
  app/src/main/res/layout/item_more.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/library_wulkanowy_api.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/scheme_preferences.xml
  app/src/test/java/io/github/wulkanowy/ui/login/LoginPresenterTest.kt
  app/src/test/java/io/github/wulkanowy/ui/main/MainPresenterTest.kt
  build.gradle
Labels: app, architecture, hacktoberfest, ui

#172 Fix range of days in exam navigation
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamPresenter.kt
Labels: hacktoberfest, hotfix, ui

#173 Dark theme refactor
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashView.kt
  app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt
  app/src/main/res/drawable/ic_menu_main_timetable_24dp.xml
  app/src/main/res/layout/fragment_attendance.xml
  app/src/main/res/layout/fragment_exam.xml
  app/src/main/res/layout/fragment_timetable.xml
  app/src/main/res/layout/item_more.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/scheme_preferences.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/splash/SplashPresenterTest.kt
Labels: hacktoberfest, ui

#174 Fix lesson sorting
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
Labels: hacktoberfest, hotfix, ui
