Repository wulkanowy/wulkanowy, pull requests merged in 2019-01, with the labels that each got.

#206 Change icon of the attendance summary
  app/build.gradle
  app/src/main/res/drawable/ic_menu_main_attendance_summary_24dp.xml
  app/src/main/res/menu/action_menu_attendance.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: ui

#209 Fix item sorting in grades details
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
Labels: fix, ux

#207 Fix spinner dropdown arrow not displaying in attendance summary
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryFragment.kt
  app/src/main/res/layout/fragment_attendance_summary.xml
  app/src/main/res/layout/item_attendance_summary.xml
  app/src/main/res/layout/item_attendance_summary_subject.xml
Labels: fix, ui, ux

#210 Fix scroll to start in grade fragment
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryFragment.kt
Labels: fix

#211 Fix stable id in grade fragment
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsHeader.kt
Labels: fix

#205 Add chucker okhttp inspector
  .travis.yml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/base/session/SessionErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences.xml
Labels: new feature

#213 Fix crash on duplicate grades
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsHeader.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsItem.kt
Labels: fix

#215 Fix crash on Meizu devices
  app/src/main/res/layout/fragment_login_form.xml
Labels: fix

#217 Fix exam_no_items english translation
  app/src/main/res/values/strings.xml
Labels: fix

#218 Fix crash on duplicate notes
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteItem.kt
Labels: fix

#219 Add more logging
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/options/LoginOptionsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessagePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MorePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NotePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
Labels: enhancement

#220 Add api initialization to the message repository
  app/src/main/java/io/github/wulkanowy/data/repositories/MessagesRepository.kt
  app/src/main/java/io/github/wulkanowy/services/job/SyncWorker.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: fix

#222 Disable code obfuscation in R8
  app/build.gradle
  app/proguard-rules.pro
  gradle.properties
Labels: fix

#223 Change icon of semester switch
  app/src/main/res/drawable/ic_menu_grade_semester_24dp.xml
Labels: ui, ux

#224 Fix empty Maybe in student repository
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/services/job/SyncWorker.kt
Labels: fix

#225 Fix receiving a lot of notifications after turning them off for a while
  app/src/main/java/io/github/wulkanowy/services/job/SyncWorker.kt
Labels: fix, sync

#226 Fix empty fragment list in fragment manager
  app/src/main/java/io/github/wulkanowy/ui/base/BaseFragmentPagerAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BasePagerAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeModule.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginModule.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageModule.kt
Labels: architecture, fix

#227 Remove renaming source file in R8
  app/proguard-rules.pro
  build.gradle
Labels: fix

#228 Upgrade to Gradle Play Publisher v2
  .circleci/config.yml
  .travis.yml
  app/build.gradle
  app/src/main/ic_launcher-web.png
  app/src/main/play/contact-email.txt
  app/src/main/play/contact-phone.txt
  app/src/main/play/contact-website.txt
  app/src/main/play/default-language.txt
  app/src/main/play/listings/pl-PL/full-description.txt
  app/src/main/play/listings/pl-PL/graphics/feature-graphic/feature.png
  app/src/main/play/listings/pl-PL/graphics/icon/icon.png
  app/src/main/play/listings/pl-PL/graphics/phone-screenshots/account-switcher.png
  app/src/main/play/listings/pl-PL/graphics/phone-screenshots/attendance-dialog.png
  app/src/main/play/listings/pl-PL/graphics/phone-screenshots/attendance-statistics.png
  app/src/main/play/listings/pl-PL/graphics/phone-screenshots/grades.png
  app/src/main/play/listings/pl-PL/graphics/phone-screenshots/more.png
  app/src/main/play/listings/pl-PL/graphics/phone-screenshots/timetable-dialog.png
  app/src/main/play/listings/pl-PL/graphics/phone-screenshots/timetable-widget.png
  app/src/main/play/listings/pl-PL/short-description.txt
  app/src/main/play/listings/pl-PL/title.txt
  app/src/main/play/pl-PL/listing/icon/icon.png
  app/src/main/play/pl-PL/listing/video
  app/src/main/play/release-notes/pl-PL/default.txt
  build.gradle
Labels: ci

#216 [Feature] Lucky numbers
  .travis.yml
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/LuckyNumberLocalTest.kt
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/LuckyNumberDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/LuckyNumber.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration2.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/LuckyNumberRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/local/LuckyNumberLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/remote/LuckyNumberRemote.kt
  app/src/main/java/io/github/wulkanowy/services/job/SyncWorker.kt
  app/src/main/java/io/github/wulkanowy/services/notification/LuckyNumberNotification.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainModule.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MorePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreView.kt
  app/src/main/res/drawable-anydpi-v24/ic_stat_notify_lucky_number.xml
  app/src/main/res/drawable-hdpi/ic_stat_notify_lucky_number.png
  app/src/main/res/drawable-mdpi/ic_stat_notify_lucky_number.png
  app/src/main/res/drawable-xhdpi/ic_stat_notify_lucky_number.png
  app/src/main/res/drawable-xxhdpi/ic_stat_notify_lucky_number.png
  app/src/main/res/drawable/ic_more_lucky_number_24dp.xml
  app/src/main/res/layout/fragment_lucky_number.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/data/repositories/remote/LuckyNumberRemoteTest.kt
Labels: new feature
