Repository wulkanowy/wulkanowy, pull requests merged in 2019-06, with the labels that each got.

#344 Add mobile access managment
  .circleci/config.yml
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/15.json
  app/src/androidTest/java/io/github/wulkanowy/data/db/migrations/AbstractMigrationTest.kt
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/MobileDeviceDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/MobileDevice.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration15.kt
  app/src/main/java/io/github/wulkanowy/data/pojos/MobileDeviceToken.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/mobiledevice/MobileDeviceLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/mobiledevice/MobileDeviceRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/mobiledevice/MobileDeviceRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainModule.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDeviceAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDeviceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDeviceItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDeviceModule.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDevicePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDeviceView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/token/MobileDeviceTokenDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/token/MobileDeviceTokenPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/token/MobileDeviceTokenVIew.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MorePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreView.kt
  app/src/main/res/drawable/ic_all_add_24dp.xml
  app/src/main/res/drawable/ic_menu_main_mobile_devices_24dp.xml
  app/src/main/res/drawable/ic_message_delete_24dp.xml
  app/src/main/res/layout/dialog_mobile_device.xml
  app/src/main/res/layout/fragment_mobile_device.xml
  app/src/main/res/layout/item_mobile_device.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/data/repositories/mobiledevice/MobileDeviceRepositoryTest.kt
Labels: new feature

#397 Change timeout string
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: ui

#399 Fix tab layout crash on prelolipop
  app/build.gradle
Labels: fix

#398 Add githook plugin
  app/build.gradle
  app/hooks.gradle
  app/play-publish-lint.sh
  app/src/main/play/release-notes/pl-PL/default.txt
  build.gradle
Labels: enhancement

#400 Add option to force calc average by app
  .travis.yml
  app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProvider.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
Labels: enhancement, new feature

#403 Fix crash TabLayout on Android 4.x in new version of material components
  app/build.gradle
  app/proguard-rules.pro
Labels: fix

#402 Fix change of worker specs after app update
  app/src/fdroid/java/io/github/wulkanowy/utils/CrashlyticsUtils.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/di/AppModule.kt
  app/src/main/java/io/github/wulkanowy/services/sync/SyncManager.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/AppInfo.kt
  app/src/play/java/io/github/wulkanowy/utils/CrashlyticsUtils.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
Labels: fix, sync

#405 Fix typo in service interval
  app/src/main/res/values-pl/value_prefernces.xml
Labels: fix

#404 Organize AndroidX libraries
  .travis.yml
  app/build.gradle
Labels: enhancement

#406 Fix update of grades in GradeDetailsFragment
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
Labels: fix

#407 Fix showing empty view in mobile device view
  app/src/main/java/io/github/wulkanowy/data/repositories/mobiledevice/MobileDeviceRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDeviceAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDeviceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDevicePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDeviceView.kt
  app/src/main/res/layout/fragment_mobile_device.xml
Labels: fix, ui

#408 Add StackOverflowError to RxJava's error handler
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
Labels: enhancement

#420 Fix crash on login when error message is null
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolPresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/StringExtension.kt
Labels: fix
