Repository wulkanowy/wulkanowy, pull requests merged in 2019-08, with the labels that each got.

#455 Update gitignore
  .gitignore
  .idea/gradle.xml
  app/.gitignore
  app/key-encrypted.p12
  app/upload-key-encrypted.jks
Labels: code style

#459 Fix day/week navigation on holidays
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsPresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/TimeExtension.kt
  app/src/test/java/io/github/wulkanowy/utils/TimeExtensionTest.kt
Labels: fix

#328 Add outline icons
  app/src/main/res/drawable/ic_about_discord.xml
  app/src/main/res/drawable/ic_about_feedback.xml
  app/src/main/res/drawable/ic_about_homepage.xml
  app/src/main/res/drawable/ic_about_privacy.xml
  app/src/main/res/drawable/ic_all_account.xml
  app/src/main/res/drawable/ic_main_attendance.xml
  app/src/main/res/drawable/ic_main_exam.xml
  app/src/main/res/drawable/ic_main_grade.xml
  app/src/main/res/drawable/ic_main_more.xml
  app/src/main/res/drawable/ic_main_timetable.xml
  app/src/main/res/drawable/ic_menu_attendance_summary.xml
  app/src/main/res/drawable/ic_menu_grade_semester.xml
  app/src/main/res/drawable/ic_menu_message_delete.xml
  app/src/main/res/drawable/ic_menu_message_forward.xml
  app/src/main/res/drawable/ic_menu_message_reply.xml
  app/src/main/res/drawable/ic_menu_message_send.xml
  app/src/main/res/drawable/ic_menu_message_write.xml
  app/src/main/res/drawable/ic_menu_timetable_lessons_completed.xml
  app/src/main/res/drawable/ic_more_homework.xml
  app/src/main/res/drawable/ic_more_lucky_number.xml
  app/src/main/res/drawable/ic_more_messages.xml
  app/src/main/res/drawable/ic_more_note.xml
  app/src/main/res/drawable/ic_more_settings.xml
Labels: ui
