Repository wulkanowy/wulkanowy, pull requests merged in 2019-02, with the labels that each got.

#237 Fix uninitialized fragment after restoring the activity
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseFragmentPagerAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageFragment.kt
Labels: architecture, fix

#242 Fix lucky number crash
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberFragment.kt
Labels: fix

#243 Fix no current student
  app/build.gradle
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/StudentLocalTest.kt
  app/src/main/java/io/github/wulkanowy/data/db/SharedPrefHelper.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/local/StudentLocal.kt
  app/src/main/java/io/github/wulkanowy/services/job/SyncWorker.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/widgets/timetable/TimetableWidgetFactory.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/splash/SplashPresenterTest.kt
Labels: architecture, fix

#239 Apply ripple effect on grade details header only if item is expandable
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsHeader.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsHeaderItemDecoration.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/res/layout/header_exam.xml
  app/src/main/res/layout/header_grade_details.xml
  app/src/main/res/layout/item_account.xml
  app/src/main/res/layout/item_attendance.xml
  app/src/main/res/layout/item_exam.xml
  app/src/main/res/layout/item_grade_details.xml
  app/src/main/res/layout/item_homework.xml
  app/src/main/res/layout/item_login_options.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/item_more.xml
  app/src/main/res/layout/item_note.xml
  app/src/main/res/layout/item_timetable.xml
Labels: ui, ux

#248 Entities unification
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/AttendanceLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/CompletedLessonsLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/ExamLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/LuckyNumberLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/StudentLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/TimetableLocalTest.kt
  app/src/main/java/io/github/wulkanowy/data/ApiHelper.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Attendance.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/AttendanceSummary.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/CompletedLesson.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Exam.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Grade.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/GradeSummary.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Homework.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/LuckyNumber.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Message.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Note.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Semester.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Student.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Subject.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Timetable.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration4.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentRemote.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/GradeExtension.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
Labels: code style

#229 Update login form to Material Design 2
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolView.kt
  app/src/main/java/io/github/wulkanowy/utils/EditTextExtension.kt
  app/src/main/res/drawable/ic_login_outlined_border.xml
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/layout/fragment_login_symbol.xml
  app/src/main/res/layout/item_widget_timetable.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ui, ux

#250 Fix timetable widget crash on update
  app/src/main/java/io/github/wulkanowy/services/widgets/TimetableWidgetService.kt
  app/src/main/java/io/github/wulkanowy/ui/widgets/timetable/TimetableWidgetFactory.kt
  app/src/main/res/xml/provider_widget_timetable.xml
Labels: fix

#252 Login form style fix
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/layout/fragment_login_symbol.xml
Labels: ui

#253 Mark as read items older than student registration date
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/StudentLocalTest.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/NoteDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Note.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Student.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration5.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/grade/GradeRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/note/NoteLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/note/NoteRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/note/NoteRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentRemote.kt
  app/src/main/java/io/github/wulkanowy/services/job/SyncWorker.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NotePresenter.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
Labels: fix

#255 Fill login credentials with default values upon fakelog selection
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/res/values/api_endpoints.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
Labels: enhancement

#232 Sending messages
  app/build.gradle
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/AttendanceLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/CompletedLessonsLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/ExamLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/LuckyNumberLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/RecipientLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/local/TimetableLocalTest.kt
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/Converters.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/RecipientDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/ReportingUnitDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Recipient.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/ReportingUnit.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Semester.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration6.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/recipient/RecipientLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/recipient/RecipientRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/recipient/RecipientRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/reportingunit/ReportingUnitLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/reportingunit/ReportingUnitRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/reportingunit/ReportingUnitRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterRemote.kt
  app/src/main/java/io/github/wulkanowy/services/job/SyncWorker.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainModule.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessagePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessageFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessagePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessageView.kt
  app/src/main/res/drawable/ic_menu_send_message_24dp.xml
  app/src/main/res/drawable/ic_send_message_24dp.xml
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/layout/fragment_send_message.xml
  app/src/main/res/menu/action_menu_send_message.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: new feature
