Repository wulkanowy/wulkanowy, pull requests merged in 2019-03, with the labels that each got.

#258 Mitigate notifications from old grades
  app/build.gradle
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/TestInternetObservingStrategy.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/attendance/AttendanceLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/completedlessons/CompletedLessonsLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/exam/ExamLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/grade/GradeEntityFactory.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/grade/GradeLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/grade/GradeRepositoryTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/luckynumber/LuckyNumberLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/recipient/RecipientLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/student/StudentLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TimetableLocalTest.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/grade/GradeRepository.kt
Labels: fix

#260 Update login error message
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: ui

#231 Update grade colors
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/GradeExtension.kt
  app/src/main/res/values/colors.xml
Labels: ui

#262 Settings rename view section
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: ui

#251 Add grade statistics
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/grade/GradeStatisticsLocalTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/GradeStatisticsDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/GradeStatistics.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration7.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/subject/SubjectRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/CustomTabLayout.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeModule.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsView.kt
  app/src/main/java/io/github/wulkanowy/utils/SpinnerExtension.kt
  app/src/main/res/layout/fragment_grade.xml
  app/src/main/res/layout/fragment_grade_details.xml
  app/src/main/res/layout/fragment_grade_statistics.xml
  app/src/main/res/layout/fragment_grade_summary.xml
  app/src/main/res/layout/item_login_options.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/data/repositories/remote/GradeStatisticsRemoteTest.kt
Labels: new feature

#265 Mitigate disappearing room numbers in timetable
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/grade/TestGradeEntityCreator.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TestTimetableEntityCreator.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TimetableLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TimetableRepositoryTest.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/timetable/TimetableRepository.kt
  app/src/main/java/io/github/wulkanowy/utils/TimeExtension.kt
  build.gradle
Labels: enhancement

#267 Fix timetable widget automatic day switching
  app/src/main/java/io/github/wulkanowy/di/AppModule.kt
  app/src/main/java/io/github/wulkanowy/ui/widgets/timetable/TimetableWidgetFactory.kt
  app/src/main/java/io/github/wulkanowy/ui/widgets/timetable/TimetableWidgetProvider.kt
Labels: architecture, fix

#269 Add missing text when no grade description
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsView.kt
  app/src/main/res/layout/dialog_grade.xml
Labels: fix, ui

#271 Add debug notification for worker
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/services/sync/SyncManager.kt
  app/src/main/java/io/github/wulkanowy/services/sync/SyncWorker.kt
  app/src/main/java/io/github/wulkanowy/services/sync/channels/DebugChannel.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences.xml
Labels: enhancement

#270 Disable swipe to refresh on data loading
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NotePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsView.kt
Labels: ux

#272 Change login progress bars
  app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberPresenter.kt
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/layout/fragment_login_student_select.xml
  app/src/main/res/layout/fragment_login_symbol.xml
  app/src/main/res/layout/fragment_lucky_number.xml
  app/src/main/res/layout/item_login_student_select.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
Labels: ui

#275 Improve the display of changes in the timetable
  app/build.gradle
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TestTimetableEntityCreator.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Timetable.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration8.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/timetable/TimetableRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/timetable/TimetableRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/widgets/timetable/TimetableWidgetFactory.kt
  app/src/main/java/io/github/wulkanowy/ui/widgets/timetable/TimetableWidgetProvider.kt
  app/src/main/res/layout/dialog_timetable.xml
  app/src/main/res/layout/item_widget_timetable.xml
  app/src/main/res/layout/widget_timetable.xml
Labels: ui, ux

#277 Follow current grade scheme in stats chart
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsView.kt
  app/src/main/java/io/github/wulkanowy/utils/GradeExtension.kt
  app/src/main/res/layout/dialog_grade.xml
  app/src/main/res/layout/item_grade_details.xml
  app/src/main/res/values/colors.xml
Labels: ui

#282 Change settings for checking the internet connection
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
Labels: enhancement

#280 Add homepage button in about fragment
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutView.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: ui

#284 Change homework view to weekly
  app/src/main/java/io/github/wulkanowy/data/db/dao/HomeworkDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/homework/HomeworkLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/homework/HomeworkRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/homework/HomeworkRepository.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/HomeworkWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/TimetableWork.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkHeader.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkView.kt
  app/src/main/res/layout/header_homework.xml
Labels: enhancement, ui, ux

#283 Move Sign in button
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/layout/fragment_login_symbol.xml
Labels: ui

#285 Change grade weightValue type to double
  .travis.yml
  app/build.gradle
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/grade/GradeLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/grade/GradeRepositoryTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/grade/TestGradeEntityCreator.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Grade.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration11.kt
  app/src/test/java/io/github/wulkanowy/utils/GradeExtensionTest.kt
Labels: fix

#286 Fix the application finish after selecting an account
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessageActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessagePresenter.kt
Labels: fix

#287 Add swipe refresh to grade fragment
  .travis.yml
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeView.kt
  app/src/main/res/layout/fragment_grade.xml
Labels: enhancement, fix, ui

#289 Fix empty container id in grade fragemnt adapter
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradePresenter.kt
Labels: fix

#288 Forwarding messages
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration11.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessageActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessagePresenter.kt
  app/src/main/res/drawable/ic_message_forward_24dp.xml
  app/src/main/res/menu/action_menu_message_preview.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: new feature

#294 Remove retry sync work when completed lessons is disabled
  app/src/main/java/io/github/wulkanowy/services/sync/SyncWorker.kt
Labels: enhancement, sync

#293 Fix restoring the grade fragment
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainModule.kt
Labels: fix

#295 Add checking current student in background services
  .travis.yml
  app/src/main/java/io/github/wulkanowy/services/sync/SyncWorker.kt
  app/src/main/java/io/github/wulkanowy/ui/widgets/timetable/TimetableWidgetFactory.kt
Labels: enhancement, sync

#296 Set max concurrency in sync worker
  app/src/main/java/io/github/wulkanowy/services/sync/SyncWorker.kt
Labels: enhancement, sync

#297 Fix issues when loading lucky number
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberPresenter.kt
Labels: fix, ux

#298 Fix reset button in timetable widget
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/ui/widgets/timetable/TimetableWidgetProvider.kt
Labels: fix

#299 Fix reselecting root fragments
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
Labels: fix

#301 Fix day navigation unevenition
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsPresenter.kt
Labels: fix, ui

#303 Fix crash on duplicate items
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableItem.kt
Labels: fix

#304 Fix more than one current semester in database
  app/src/main/java/io/github/wulkanowy/data/db/dao/SemesterDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterRepository.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/UnitTestInternetObservingStrategy.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/attendance/AttendanceRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/completedlessons/CompletedLessonsRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/exam/ExamRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/luckynumber/LuckyNumberRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/semester/SemesterRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/semester/TestSemesterEnityCreator.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/student/StudentRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/timetable/TimetableRemoteTest.kt
Labels: db, fix

#306 Fix undeliverable network exceptions
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
Labels: fix

#305 Fix rejected execution in sync worker
  app/src/main/java/io/github/wulkanowy/services/sync/SyncWorker.kt
Labels: fix, sync

#308 Fix black spinner in login form
  app/src/main/res/drawable/ic_login_outlined_border.xml
Labels: fix, ui

#311 Fix more than one current student
  .travis.yml
  app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentLocal.kt
Labels: db, fix

#310 Again fix rejected execution in sync worker
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/services/sync/SyncManager.kt
Labels: fix, sync

#312 Add opening login view on no current student
  app/src/main/java/io/github/wulkanowy/data/exceptions/NoCurrentStudent.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/base/session/BaseSessionFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/base/session/BaseSessionPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/base/session/BaseSessionView.kt
  app/src/main/java/io/github/wulkanowy/ui/base/session/SessionErrorHandler.kt
Labels: enhancement, fix, ux

#307 Fix more than one current semester
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/11.json
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/12.json
  app/src/androidTest/java/io/github/wulkanowy/data/db/migrations/Migration12Test.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/recipient/RecipientLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/student/StudentLocalTest.kt
  app/src/main/java/io/github/wulkanowy/data/ApiHelper.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/SemesterDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Student.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration12.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentRemote.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/student/StudentRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
Labels: db, fix

#313 Add 0,75 grade modifier
  app/src/main/res/values-pl/value_prefernces.xml
  app/src/main/res/values/value_prefernces.xml
Labels: ui

#290 Add deleting messages
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessagePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessageActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessagePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/main/res/drawable/ic_message_delete_24dp.xml
  app/src/main/res/layout/fragment_message_preview.xml
  app/src/main/res/menu/action_menu_message_preview.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: new feature
