Repository wulkanowy/wulkanowy, pull requests merged in 2019-05, with the labels that each got.

#337 Fix not attached fragment
  app/src/main/java/io/github/wulkanowy/ui/base/BaseActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetProvider.kt
Labels: fix

#338 Fix crash when no webview activity
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/utils/ActivityExtension.kt
  app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt
Labels: fix

#339 Fix crash on reselecting fragment
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
Labels: fix, ux

#340 Fix null returns in widgets
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetProvider.kt
  build.gradle
Labels: fix

#341 Don't copy teacher from previous lesson to completed
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TestTimetableEntityCreator.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TimetableRepositoryTest.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/timetable/TimetableRepository.kt
Labels: sync

#343 Fix empty maybe when loading message content
  app/src/main/java/io/github/wulkanowy/data/db/dao/MessagesDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabView.kt
Labels: fix

#342 Fix no current student in services after logout all accounts
  .travis.yml
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/services/sync/SyncWorker.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetProvider.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/splash/SplashPresenterTest.kt
Labels: fix

#345 Change help text when entering the symbol to a more precise one
  app/build.gradle
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: ux

#348 Fix network constraint in background sync
  app/src/main/java/io/github/wulkanowy/services/sync/SyncManager.kt
Labels: fix, sync

#394 Fix only wifi setting
  app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt
Labels: fix, sync

#374 Show grades average from register if exist instead of calculating
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/14.json
  app/src/androidTest/java/io/github/wulkanowy/data/db/migrations/AbstractMigrationTest.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/GradeSummary.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration14.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/gradessummary/GradeSummaryRemote.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt
  app/src/main/res/layout/item_grade_summary.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
  app/src/test/java/io/github/wulkanowy/utils/GradeExtensionTest.kt
Labels: enhancement, new feature
