Repository wulkanowy/wulkanowy, pull requests merged in 2019-04, with the labels that each got.

#315 Add class name to student
  .travis.yml
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/13.json
  app/src/androidTest/java/io/github/wulkanowy/data/db/migrations/AbstractMigrationTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/db/migrations/Migration12Test.kt
  app/src/androidTest/java/io/github/wulkanowy/data/db/migrations/Migration13Test.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/attendance/AttendanceLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/completedlessons/CompletedLessonsLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/exam/ExamLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/grade/GradeLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/luckynumber/LuckyNumberLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/recipient/RecipientLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/student/StudentLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TimetableLocalTest.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Semester.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Student.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration13.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentRemote.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectItem.kt
  app/src/main/res/layout/item_account.xml
  app/src/test/java/io/github/wulkanowy/data/repositories/semester/TestSemesterEnityCreator.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/student/StudentRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
Labels: enhancement

#319 Fix message loading if student and parent are logged in
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration13.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRepository.kt
Labels: db, fix

#314 Add account picker for timetable widget
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/data/db/SharedPrefHelper.kt
  app/src/main/java/io/github/wulkanowy/di/BuilderModule.kt
  app/src/main/java/io/github/wulkanowy/services/widgets/TimetableWidgetService.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigureActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigureItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigurePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigureView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetProvider.kt
  app/src/main/java/io/github/wulkanowy/utils/TimeExtension.kt
  app/src/main/res/drawable-hdpi/ic_widget_account.png
  app/src/main/res/drawable-mdpi/ic_widget_account.png
  app/src/main/res/drawable-xhdpi/ic_widget_account.png
  app/src/main/res/drawable-xxhdpi/ic_widget_account.png
  app/src/main/res/drawable/img_timetable_widget_preview.png
  app/src/main/res/layout/activity_timetable_widget_configure.xml
  app/src/main/res/layout/item_account.xml
  app/src/main/res/layout/item_widget_timetable.xml
  app/src/main/res/layout/widget_timetable.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/provider_widget_timetable.xml
Labels: new feature, ui, ux

#321 Change style of privacy policy link
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
Labels: ui, ux

#322 Add counting of the full-year average to the summary of grades
  app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pl/value_prefernces.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/value_prefernces.xml
  app/src/main/res/xml/scheme_preferences.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
Labels: new feature, ui, ux

#318 Add a selection of multiple students to login
  app/build.gradle
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/student/StudentLocalTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectView.kt
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/layout/fragment_login_student_select.xml
  app/src/main/res/layout/fragment_login_symbol.xml
  app/src/main/res/layout/item_login_student_select.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
Labels: new feature, ui, ux

#279 Add AMOLED mode
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/di/AppModule.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/LuckyNumberWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/MessageWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/NoteWork.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/base/ThemeManager.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/res/drawable/ic_login_outlined_border.xml
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pl/value_prefernces.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/value_prefernces.xml
  app/src/main/res/xml/scheme_preferences.xml
Labels: ui

#324 Fix grade summary final grade string
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt
  app/src/main/res/layout/item_grade_summary.xml
Labels: fix

#326 Fix showing last message after update
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabFragment.kt
Labels: fix, ui

#325 Fix configure activity's theme
  app/src/main/java/io/github/wulkanowy/ui/base/ThemeManager.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashActivity.kt
  app/src/main/res/values-pl/strings.xml
Labels: fix, ui

#327 Add activity and fragment lifecycle logging
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/di/AppModule.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessagePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessagePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MorePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NotePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/FirebaseAnalyticsHelper.kt
  app/src/main/java/io/github/wulkanowy/utils/LoggerUtils.kt
  build.gradle
Labels: enhancement

#329 Improve login student selection layout
  app/src/main/res/layout/item_login_student_select.xml
Labels: ui

#331 Add showing proper fragment in notifications
  app/src/main/java/io/github/wulkanowy/services/sync/works/GradeWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/LuckyNumberWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/MessageWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/NoteWork.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigurePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetProvider.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/main/MainPresenterTest.kt
Labels: ux

#332 Fix theme on release build
  app/src/main/java/io/github/wulkanowy/ui/base/ThemeManager.kt
Labels: fix, ui

#333 Fix menu view initialization and restoration
  .travis.yml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/services/sync/works/GradeWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/LuckyNumberWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/MessageWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/NoteWork.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetProvider.kt
Labels: fix, ux

#334 Fix dark theme background with custom theme engine
  app/src/main/res/values-night/styles.xml
Labels: ui

#335 Fix entity list comparing
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/grade/GradeRepositoryTest.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/attendance/AttendanceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/attendancesummary/AttendanceSummaryRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/completedlessons/CompletedLessonsRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/exam/ExamRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/grade/GradeRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/gradessummary/GradeSummaryRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/homework/HomeworkRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/note/NoteRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/recipient/RecipientRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/reportingunit/ReportingUnitRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/subject/SubjectRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/timetable/TimetableRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashActivity.kt
  app/src/main/java/io/github/wulkanowy/utils/ListExtension.kt
Labels: fix, sync
