Repository wulkanowy/wulkanowy, pull requests merged in 2019-09, with the labels that each got.

#474 Update dependencies
  app/build.gradle
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/student/StudentLocalTest.kt
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/data/db/SharedPrefProvider.kt
  app/src/main/java/io/github/wulkanowy/di/AppComponent.kt
  app/src/main/java/io/github/wulkanowy/di/BindingModule.kt
  app/src/main/java/io/github/wulkanowy/services/ServicesModule.kt
  app/src/main/java/io/github/wulkanowy/services/sync/SyncManager.kt
  app/src/main/java/io/github/wulkanowy/services/sync/channels/DebugChannel.kt
  app/src/main/java/io/github/wulkanowy/services/sync/channels/NewEntriesChannel.kt
  app/src/main/java/io/github/wulkanowy/services/widgets/TimetableWidgetService.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseFragmentPagerAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/license/LicenseFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigurePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigurePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetProvider.kt
  app/src/main/java/io/github/wulkanowy/utils/ActivityExtension.kt
  app/src/main/java/io/github/wulkanowy/utils/EditTextExtension.kt
  gradle.properties
Labels: dependencies

#477 Fix empty hosts list after activity recreating
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
Labels: fix

#476 Fix spaming NoCurentStudentException
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetProvider.kt
Labels: enhancement, fix

#484 Fix status bar color on xiaomi
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values-v21/styles.xml
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/styles.xml
Labels: ui

#485 Mitigate disappearing teachers in timetable
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TestTimetableEntityCreator.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TimetableRepositoryTest.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/timetable/TimetableRepository.kt
Labels: sync

#486 Change marking current student in accounts dialog
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountItem.kt
  app/src/main/res/layout/item_account.xml
  app/src/main/res/values-night/styles.xml
Labels: ui

#487 Fix about_feedback_summary PL typo
  app/src/main/res/values-pl/strings.xml
Labels: ui

#492 Fix crashing tab layout on prelolipop
  app/proguard-rules.pro
Labels: fix

#488 Fix account icon color in widgets
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigureItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigureItem.kt
  app/src/main/res/drawable-night/ic_account_circular_border.xml
  app/src/main/res/drawable/ic_account_circular_border.xml
Labels: fix, ui

#494 Fix grade details header unread info
  app/src/main/res/layout/header_grade_details.xml
Labels: fix, ui

#493 Fix login in symbol view
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
Labels: fix

#511 Fix attendance_excused_lateness pl typo
  app/src/main/res/values-pl/strings.xml
Labels: fix, ui

#508 Fix privacy link position on small screens
  app/src/main/res/layout/fragment_login_form.xml
Labels: fix, ui

#507 Fix wrong index in form host value
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
Labels: fix

#519 Improve date navigation
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsPresenter.kt
  app/src/main/res/drawable/ic_chevron_left.xml
  app/src/main/res/drawable/ic_chevron_right.xml
  app/src/main/res/layout/fragment_attendance.xml
  app/src/main/res/layout/fragment_exam.xml
  app/src/main/res/layout/fragment_homework.xml
  app/src/main/res/layout/fragment_timetable.xml
  app/src/main/res/layout/fragment_timetable_completed.xml
Labels: ui

#489 Add teachers
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/16.json
  app/src/androidTest/java/io/github/wulkanowy/data/db/migrations/AbstractMigrationTest.kt
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/TeacherDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Teacher.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration16.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/teacher/TeacherLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/teacher/TeacherRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/teacher/TeacherRepository.kt
  app/src/main/java/io/github/wulkanowy/services/ServicesModule.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/TeacherWork.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainModule.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MorePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/teacher/TeacherFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/teacher/TeacherItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/teacher/TeacherPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/teacher/TeacherView.kt
  app/src/main/res/drawable/ic_more_teacher.xml
  app/src/main/res/layout/fragment_teacher.xml
  app/src/main/res/layout/item_teacher.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: new feature
