Repository wulkanowy/wulkanowy, pull requests merged in 2019-10, with the labels that each got.

#532 Update readme badges
  README.en.md
  README.md
Labels: hacktoberfest

#531 Add click to copy function
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/token/MobileDeviceTokenDialog.kt
Labels: new feature, ui

#535 Clear Semesters table
  app/build.gradle
  app/src/androidTest/java/io/github/wulkanowy/data/db/migrations/AbstractMigrationTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/db/migrations/Migration13Test.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration17.kt
Labels: db, hotfix

#530 Change timetable widget date format
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetProvider.kt
Labels: ui

#513 Add better timetable changes display
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
  app/src/main/res/layout/dialog_lesson_completed.xml
  app/src/main/res/layout/dialog_timetable.xml
  app/src/main/res/layout/item_completed_lesson.xml
  app/src/main/res/layout/item_timetable.xml
  app/src/main/res/layout/item_widget_timetable.xml
  app/src/main/res/layout/item_widget_timetable_dark.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, ui

#546 Update mockito to last version from maven central
  app/build.gradle
  build.gradle
Labels: dependencies

#548 Fix duplicate percentage in attendance summary
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryFragment.kt
Labels: fix, hacktoberfest

#534 Add mark as read button enable logic
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsView.kt
  app/src/main/res/menu/action_menu_grade_details.xml
Labels: new feature, ui

#547 Add navigate up to login view
  .idea/codeStyles/Project.xml
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginView.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_login_student_select.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/login/LoginPresenterTest.kt
Labels: hacktoberfest, new feature, ux

#553 Update androidx dependencies
  app/build.gradle
  app/src/main/res/layout/activity_main.xml
Labels: dependencies, hacktoberfest

#555 Move default preferences values to separate file
  app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt
  app/src/main/res/values-pl/preferences_values.xml
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_values.xml
  app/src/main/res/xml/scheme_preferences.xml
Labels: enhancement, hacktoberfest

#554 Add system theme setting for Android 10
  app/src/main/java/io/github/wulkanowy/ui/base/ThemeManager.kt
  app/src/main/res/values-pl-v29/preferences_values.xml
  app/src/main/res/values-pl/preferences_values.xml
  app/src/main/res/values-v29/preferences_defaults.xml
  app/src/main/res/values-v29/preferences_values.xml
  app/src/main/res/values/preferences_values.xml
Labels: hacktoberfest, new feature, ux

#556 Contact info after failed login
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolView.kt
  app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/layout/fragment_login_student_select.xml
  app/src/main/res/layout/fragment_login_symbol.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, ui, ux

#557 Add school info
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/18.json
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/SchoolDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/TeacherDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/School.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration18.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/school/SchoolLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/school/SchoolRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/school/SchoolRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/teacher/TeacherLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/teacher/TeacherRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainModule.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MorePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/SchoolAndTeachersChildView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/SchoolAndTeachersFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/SchoolAndTeachersModule.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/SchoolAndTeachersPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/SchoolAndTeachersView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/school/SchoolFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/school/SchoolPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/school/SchoolView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/teacher/TeacherFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/teacher/TeacherItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/teacher/TeacherPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/teacher/TeacherView.kt
  app/src/main/java/io/github/wulkanowy/utils/FragmentExtension.kt
  app/src/main/res/drawable/ic_more_schoolandteachers.xml
  app/src/main/res/drawable/ic_more_teacher.xml
  app/src/main/res/layout/fragment_school.xml
  app/src/main/res/layout/fragment_schoolandteachers.xml
  app/src/main/res/layout/fragment_teacher.xml
  app/src/main/res/layout/item_teacher.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: hacktoberfest, new feature

#536 Change FAB to extended FAB in messages
  app/src/main/res/layout/fragment_message.xml
Labels: ui, ux

#569 Fix restoring state in exposed dropdown menu
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginSymbolAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewFragment.kt
  app/src/main/res/layout/fragment_login_form.xml
Labels: fix, ux

#570 Add school quick actions
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/school/SchoolFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/school/SchoolPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/school/SchoolView.kt
  app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt
  app/src/main/res/drawable/ic_school_directions.xml
  app/src/main/res/drawable/ic_school_phone.xml
  app/src/main/res/layout/fragment_school.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: new feature, ui
