Repository wulkanowy/wulkanowy, pull requests merged in 2019-11, with the labels that each got.

#577 Add language change settings
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/di/AppModule.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/school/SchoolFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsView.kt
  app/src/main/java/io/github/wulkanowy/utils/AppInfo.kt
  app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt
  app/src/main/res/values-pl/preferences_values.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/preferences_values.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences.xml
Labels: new feature

#522 Add DatePicker to Timetable and Attendance modules.
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsView.kt
  app/src/main/java/io/github/wulkanowy/utils/SchooldaysRangeLimiter.kt
  app/src/main/res/layout/fragment_attendance.xml
  app/src/main/res/layout/fragment_timetable.xml
  app/src/main/res/layout/fragment_timetable_completed.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/styles.xml
Labels: new feature

#579 Update gradle wrapper
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#581 Add BaseDao interface
  app/src/main/java/io/github/wulkanowy/data/db/dao/AttendanceDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/AttendanceSummaryDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/BaseDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/CompletedLessonsDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/ExamDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/GradeDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/GradePointsStatisticsDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/GradeStatisticsDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/GradeSummaryDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/HomeworkDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/LuckyNumberDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/MessagesDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/MobileDeviceDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/NoteDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/RecipientDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/ReportingUnitDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/SchoolDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/SemesterDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/SubjectDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/TeacherDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/TimetableDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/luckynumber/LuckyNumberLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/mobiledevice/MobileDeviceLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/recipient/RecipientLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/reportingunit/ReportingUnitLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/school/SchoolLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentLocal.kt
  build.gradle
Labels: db

#583 Fix LuckyNumberWidget not showing ThemeDialog
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigurePresenter.kt
Labels: fix

#587 Update material design components
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/widgets/MaterialLinearLayout.kt
  app/src/main/java/io/github/wulkanowy/ui/widgets/MaterialTabLayout.kt
  app/src/main/res/layout/fragment_grade.xml
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/layout/fragment_schoolandteachers.xml
  app/src/main/res/menu/action_menu_attendance.xml
  app/src/main/res/menu/action_menu_grade.xml
  app/src/main/res/menu/action_menu_grade_details.xml
  app/src/main/res/menu/action_menu_main.xml
  app/src/main/res/menu/action_menu_message_preview.xml
  app/src/main/res/menu/action_menu_send_message.xml
  app/src/main/res/menu/action_menu_timetable.xml
  gradle.properties
Labels: dependencies

#589 Fix screens loading state
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDevicePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/school/SchoolFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/school/SchoolPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/school/SchoolView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/teacher/TeacherPresenter.kt
  app/src/main/res/layout/fragment_school.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: fix, ui

#596 Add 0,00 grade modifier
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/data/db/SharedPrefProvider.kt
  app/src/main/java/io/github/wulkanowy/services/sync/SyncManager.kt
  app/src/main/java/io/github/wulkanowy/utils/GradeExtension.kt
  app/src/main/res/values-pl/preferences_values.xml
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_values.xml
  app/src/test/java/io/github/wulkanowy/utils/GradeExtensionTest.kt
Labels: new feature
