Repository wulkanowy/wulkanowy, pull requests merged in 2020-05, with the labels that each got.

#788 Add importantForAutofill to login fields
  app/src/main/res/layout/fragment_login_advanced.xml
  app/src/main/res/layout/fragment_login_form.xml
Labels: fix, ux

#789 Migrate from fabric to firebase crashlytics
  .travis.yml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/utils/AppInfo.kt
  app/src/play/java/io/github/wulkanowy/utils/CrashlyticsUtils.kt
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#790 Add nav bar color in night style
  app/src/main/res/values-night/styles.xml
Labels: bug, fix

#791 Use view binding instead of kotlin synthetics
  .bettercodehub.yml
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/base/BaseActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseDialogFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/contributor/ContributorFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/license/LicenseFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/logviewer/LogViewerFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/ViewType.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/details/HomeworkDetailsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/details/HomeworkDetailsDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigureActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessageActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDeviceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/token/MobileDeviceTokenDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/SchoolAndTeachersFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/school/SchoolFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/teacher/TeacherFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigureActivity.kt
  app/src/main/java/io/github/wulkanowy/utils/LifecycleAwareVariable.kt
  app/src/main/res/layout/fragment_about.xml
  app/src/main/res/layout/fragment_contributor.xml
Labels: architecture

#792 Optimize grade average provider
  app/build.gradle
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/grade/GradeLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/grade/GradeRepositoryTest.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/grade/GradeLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/grade/GradeRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/grade/GradeRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/gradessummary/GradeSummaryLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/gradessummary/GradeSummaryRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/gradessummary/GradeSummaryRepository.kt
  app/src/main/java/io/github/wulkanowy/services/ServicesModule.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/GradeSummaryWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/GradeWork.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeDetailsWithAverage.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
Labels: enhancement, sync

#794 Update translations
  app/src/main/res/values-de/preferences_values.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/preferences_values.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/preferences_values.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/preferences_values.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: translation

#759 Add widget system theme option
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigureActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigurePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigureActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetProvider.kt
  app/src/main/res/layout/activity_widget_configure.xml
  app/src/main/res/layout/item_widget_timetable.xml
  app/src/main/res/layout/item_widget_timetable_dark.xml
  app/src/main/res/layout/item_widget_timetable_small.xml
  app/src/main/res/layout/widget_timetable.xml
  app/src/main/res/layout/widget_timetable_dark.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/api_hosts.xml
  app/src/main/res/values/strings.xml
Labels: new feature

#797 New Crowdin translations
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
Labels: translation

#806 Add fullscreen mode to homework dialog
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/details/HomeworkDetailsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/details/HomeworkDetailsDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverFragment.kt
  app/src/main/res/drawable/ic_fullscreen.xml
  app/src/main/res/drawable/ic_fullscreen_exit.xml
  app/src/main/res/layout/item_homework_dialog_details.xml
Labels: feature request

#814 Fix notifications on android 8.0
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/services/sync/SyncManager.kt
Labels: fix

#804 Add search in messages
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabView.kt
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/action_menu_message_tab.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: new feature, ui, ux

#578 Add notification about upcoming lesson
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TimetableRepositoryTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/timetable/TimetableRepository.kt
  app/src/main/java/io/github/wulkanowy/di/BindingModule.kt
  app/src/main/java/io/github/wulkanowy/services/ServicesModule.kt
  app/src/main/java/io/github/wulkanowy/services/alarm/TimetableNotificationReceiver.kt
  app/src/main/java/io/github/wulkanowy/services/alarm/TimetableNotificationSchedulerHelper.kt
  app/src/main/java/io/github/wulkanowy/services/sync/channels/UpcomingLessonsChannel.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/TimeExtension.kt
  app/src/main/res/drawable-hdpi/ic_stat_timetable.png
  app/src/main/res/drawable-mdpi/ic_stat_timetable.png
  app/src/main/res/drawable-xhdpi/ic_stat_timetable.png
  app/src/main/res/drawable-xxhdpi/ic_stat_timetable.png
  app/src/main/res/drawable-xxxhdpi/ic_stat_timetable.png
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences.xml
Labels: new feature

#550 Add lesson time left display
  app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableView.kt
  app/src/main/java/io/github/wulkanowy/utils/TimetableExtension.kt
  app/src/main/res/drawable/background_timetable_time_left.xml
  app/src/main/res/layout/item_timetable.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences.xml
  app/src/test/java/io/github/wulkanowy/TestEnityCreator.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/attendance/AttendanceRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/completedlessons/CompletedLessonsRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/exam/ExamRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/luckynumber/LuckyNumberRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/mobiledevice/MobileDeviceRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/semester/SemesterRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/timetable/TimetableRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
  app/src/test/java/io/github/wulkanowy/utils/TimetableExtensionTest.kt
Labels: new feature, ui

#808 Add app killer manager to settings
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsView.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences.xml
Labels: new feature, sync, ux

#813 New Crowdin translations
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
Labels: translation

#816 Fix crash in timetable on api < 21
  app/src/main/res/drawable/background_timetable_time_left.xml
  app/src/main/res/layout/item_timetable.xml
Labels: fix

#825 Fix grade sorting
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt
Labels: fix

#828 Fix mark message as read in search mode
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
Labels: fix

#826 Fix crash in timetable time left
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt
Labels: fix

#830 Set app_name in build.gradle
  app/build.gradle
  app/src/debug/res/values/strings.xml
  app/src/main/res/layout/fragment_attendance.xml
  app/src/main/res/layout/fragment_exam.xml
  app/src/main/res/layout/fragment_homework.xml
  app/src/main/res/layout/fragment_timetable.xml
  app/src/main/res/layout/fragment_timetable_completed.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#829 Destroy webview in password recover before setting binding to null
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverFragment.kt
Labels: fix

#836 Wrap long preference titles
  app/src/main/res/xml/scheme_preferences.xml
Labels: fix, ui, ux

#846 Fix debug channel
  app/src/main/java/io/github/wulkanowy/services/sync/channels/DebugChannel.kt
Labels: fix

#849 Fix displaying the feature disabled message in completed lessons
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsPresenter.kt
Labels: fix, ui
