Repository wulkanowy/wulkanowy, pull requests merged in 2020-09, with the labels that each got.

#933 Fix crash in flowWithResourceIn()
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/FlowUtils.kt
Labels: hotfix

#934 Add skarzyskokamienna vulcan register
  app/src/main/res/values/api_hosts.xml
Labels: uonet-update

#935 Fix recaptcha loading in password recover
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverPresenter.kt
Labels: fix

#936 Disable notification sound
  app/src/main/java/io/github/wulkanowy/services/sync/channels/UpcomingLessonsChannel.kt
Labels: enhancement

#938 Remove force sync dialog
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsView.kt
Labels: enhancement

#937 Fix lucky number notification
  app/src/main/java/io/github/wulkanowy/data/db/dao/LuckyNumberDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/luckynumber/LuckyNumberRepository.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/LuckyNumberWork.kt
Labels: fix

#941 Fix grade summary empty view
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt
Labels: fix

#940 Fix semester list refresh on no current semester found
  app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterRepository.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/semester/SemesterRepositoryTest.kt
Labels: fix

#943 Fix attendance item description
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceDialog.kt
  app/src/main/java/io/github/wulkanowy/utils/AttendanceExtension.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: fix, translation, ui

#944 Fix crash in flowWithResourceIn()
  app/src/main/java/io/github/wulkanowy/ui/base/BasePresenter.kt
Labels: fix

#945 Add full stacktrace to errors list in sync now
  app/src/main/java/io/github/wulkanowy/services/sync/SyncWorker.kt
Labels: ux

#950 Disable sound of upcoming lessons notification (fix)
  app/src/main/java/io/github/wulkanowy/services/sync/SyncManager.kt
  app/src/main/java/io/github/wulkanowy/services/sync/channels/UpcomingLessonsChannel.kt
Labels: fix

#951 Fix bug in grade statistics
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsPresenter.kt
Labels: fix

#955 Ignore empty semesters on refresh
  app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterRepository.kt
Labels: enhancement

#954 Move timetable notifications scheduling to background thread
  app/src/main/java/io/github/wulkanowy/services/alarm/TimetableNotificationSchedulerHelper.kt
Labels: enhancement

#959 Add eduportal.koszalin.pl register
  app/build.gradle
  app/src/main/res/values/api_hosts.xml
Labels: feature request

#958 Fix lifecycle of timer tasks in timetable lessons
  app/src/main/java/io/github/wulkanowy/data/Resource.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/java/io/github/wulkanowy/utils/FlowUtils.kt
  build.gradle
Labels: fix

#960 Expand exam sync date range to next month
  app/src/main/java/io/github/wulkanowy/data/repositories/exam/ExamRepository.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/ExamWork.kt
  app/src/main/java/io/github/wulkanowy/utils/TimeExtension.kt
  app/src/test/java/io/github/wulkanowy/utils/TimeExtensionTest.kt
Labels: enhancement

#967 Fix crash in flowWithResourceIn()
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/db/dao/MessagesDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Message.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/FlowUtils.kt
  app/src/test/java/io/github/wulkanowy/TestEnityCreator.kt
Labels: db, fix

#968 Upgrade gradle wrapper to 6.6.1
  .travis.yml
  app/jacoco.gradle
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies

#939 Add app shortcuts
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/res/drawable-hdpi/ic_shortcut_attendance.png
  app/src/main/res/drawable-hdpi/ic_shortcut_exam.png
  app/src/main/res/drawable-hdpi/ic_shortcut_grade.png
  app/src/main/res/drawable-hdpi/ic_shortcut_message.png
  app/src/main/res/drawable-hdpi/ic_shortcut_timetable.png
  app/src/main/res/drawable-mdpi/ic_shortcut_attendance.png
  app/src/main/res/drawable-mdpi/ic_shortcut_exam.png
  app/src/main/res/drawable-mdpi/ic_shortcut_grade.png
  app/src/main/res/drawable-mdpi/ic_shortcut_message.png
  app/src/main/res/drawable-mdpi/ic_shortcut_timetable.png
  app/src/main/res/drawable-xhdpi/ic_shortcut_attendance.png
  app/src/main/res/drawable-xhdpi/ic_shortcut_exam.png
  app/src/main/res/drawable-xhdpi/ic_shortcut_grade.png
  app/src/main/res/drawable-xhdpi/ic_shortcut_message.png
  app/src/main/res/drawable-xhdpi/ic_shortcut_timetable.png
  app/src/main/res/drawable-xxhdpi/ic_shortcut_attendance.png
  app/src/main/res/drawable-xxhdpi/ic_shortcut_exam.png
  app/src/main/res/drawable-xxhdpi/ic_shortcut_grade.png
  app/src/main/res/drawable-xxhdpi/ic_shortcut_message.png
  app/src/main/res/drawable-xxhdpi/ic_shortcut_timetable.png
  app/src/main/res/drawable-xxxhdpi/ic_shortcut_attendance.png
  app/src/main/res/drawable-xxxhdpi/ic_shortcut_exam.png
  app/src/main/res/drawable-xxxhdpi/ic_shortcut_grade.png
  app/src/main/res/drawable-xxxhdpi/ic_shortcut_message.png
  app/src/main/res/drawable-xxxhdpi/ic_shortcut_timetable.png
Labels: new feature

#947 Show subjects without grades in "Grades"
  app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences.xml
Labels: new feature

#952 Different notification for notes and praises
  app/src/main/java/io/github/wulkanowy/services/sync/works/NoteWork.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: new feature

#956 Add remembering the full screen mode in homework
  app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/details/HomeworkDetailsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/details/HomeworkDetailsDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/details/HomeworkDetailsPresenter.kt
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_keys.xml
Labels: ux

#946 Add subjects sorting in "Grades"
  app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeSortingMode.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/res/values-pl/preferences_values.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/preferences_values.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences.xml
Labels: new feature

#953 Show groups next to subjects in timetable
  app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableView.kt
  app/src/main/res/layout/item_timetable.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences.xml
Labels: new feature

#969 Migrate from gson to moshi
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/db/Converters.kt
  app/src/main/java/io/github/wulkanowy/data/pojos/Contributor.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/appcreator/AppCreatorRepository.kt
  app/src/main/res/layout/fragment_contributor.xml
  app/src/main/res/layout/item_contributor.xml
Labels: dependencies

#970 Fix string pair list type converter
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/db/Converters.kt
  app/src/main/java/io/github/wulkanowy/data/db/adapters/PairAdapterFactory.kt
  app/src/test/java/io/github/wulkanowy/data/db/ConvertersTest.kt
Labels: fix

#971 Fix string pair list type converter
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/db/adapters/PairAdapterFactory.kt
  app/src/test/java/io/github/wulkanowy/data/db/ConvertersTest.kt
Labels: fix
