Repository wulkanowy/wulkanowy, pull requests merged in 2020-12, with the labels that each got.

#1042 Fix HMS analitycs and crashlitycs
  app/src/fdroid/java/io/github/wulkanowy/utils/AnalyticsHelper.kt
  app/src/hms/java/io/github/wulkanowy/utils/AnalyticsHelper.kt
  app/src/hms/java/io/github/wulkanowy/utils/CrashLogUtils.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseDialogFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainView.kt
  app/src/play/java/io/github/wulkanowy/utils/AnalyticsHelper.kt
Labels: fix

#1041 Add register variant auto-matching based on email
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/repositories/timetable/TimetableRemote.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/res/values/api_hosts.xml
  app/src/test/java/io/github/wulkanowy/data/repositories/timetable/TimetableRemoteTest.kt
Labels: new feature, ux

#1049 New Crowdin updates
  app/src/main/res/values-cs-rCZ/strings.xml
Labels: translation

#1048 Disable recordException in hms
  app/src/hms/java/io/github/wulkanowy/utils/CrashLogUtils.kt
Labels: fix

#1050 Fix username label on registers other than default
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
Labels: fix, ux

#1052 Add log event to language setting
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt
Labels: feature request

#1055 Configure github actions
  .github/workflows/test.yml
  README.en.md
  README.md
  app/jacoco.gradle
  app/src/test/java/io/github/wulkanowy/utils/TimeExtensionTest.kt
Labels: ci

#1056 Github workflow config improvements
  .github/workflows/test.yml
  .gitignore
  settings.gradle
Labels: ci
