Repository wulkanowy/wulkanowy, pull requests merged in 2020-06, with the labels that each got.

#862 Don't capture click on login student select checkbox
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectAdapter.kt
Labels: fix, ux

#857 Filter out empty items in grade summary
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt
Labels: ux

#860 Fix capitalization in new message activity
  app/src/main/res/layout/activity_send_message.xml
Labels: ux

#859 Fix too many alarms on samsung devices
  app/src/main/java/io/github/wulkanowy/services/alarm/TimetableNotificationSchedulerHelper.kt
Labels: fix

#854 Fixes in updating adapter items
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabAdapter.kt
Labels: fix

#864 Revert "Bump sonarqube-gradle-plugin from 2.8 to 3.0"
  build.gradle
Labels: dependencies

#856 New Crowdin translations
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
Labels: translation

#863 Fix login button state in student select login fragment
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt
  app/src/main/res/layout/fragment_login_student_select.xml
Labels: fix, ux

#855 Emulate summaries from grade list when summaries are empty
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
Labels: fix

#877 Fix showing summary summary for subjects without partial grades
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProvider.kt
  app/src/main/java/io/github/wulkanowy/utils/SdkExtension.kt
Labels: fix

#871 Add account headers in student picker
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentRemote.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/Account.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountView.kt
  app/src/main/res/layout/dialog_account.xml
  app/src/main/res/layout/header_account.xml
  app/src/main/res/layout/item_account.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, new feature

#873 Fix lint errors
  app/src/androidTest/java/io/github/wulkanowy/data/db/migrations/Migration13Test.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/attendance/AttendanceLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/luckynumber/LuckyNumberLocalTest.kt
  app/src/fdroid/java/io/github/wulkanowy/utils/CrashlyticsUtils.kt
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/appcreator/AppCreatorRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/exam/ExamLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/recipient/RecipientLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/reportingunit/ReportingUnitLocal.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/GradeStatisticsWork.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/logviewer/LogViewerPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsPresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/LifecycleAwareVariable.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/TestEnityCreator.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/message/MessageRepositoryTest.kt
Labels: fix

#866 Message sharing and printing
  app/src/main/assets/message-print-page.html
  app/src/main/assets/wulkanowy-logo-black.svg
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewView.kt
  app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt
  app/src/main/res/drawable/ic_menu_message_print.xml
  app/src/main/res/drawable/ic_menu_message_share.xml
  app/src/main/res/menu/action_menu_message_preview.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: new feature

#869 Message fuzzy search
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
Labels: enhancement

#874 New Crowdin translations
  app/src/main/res/values-de/preferences_values.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/preferences_values.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/preferences_values.xml
  app/src/main/res/values-uk/strings.xml
Labels: translation
