Repository wulkanowy/wulkanowy, pull requests merged in 2020-10, with the labels that each got.

#966 Update android sdk
  .travis.yml
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessageActivity.kt
  app/src/main/java/io/github/wulkanowy/utils/LoggerUtils.kt
Labels: dependencies, hacktoberfest

#981 New Crowdin updates
  app/src/main/res/values-pl/strings.xml
Labels: hacktoberfest, ui

#988 Add support for night mode in account switcher dialog
  app/src/main/res/values/styles.xml
Labels: fix

#989 Add support for BIG font
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_about.xml
  app/src/main/res/layout/item_attendance.xml
  app/src/main/res/layout/item_attendance_summary_subject.xml
  app/src/main/res/layout/item_completed_lesson.xml
  app/src/main/res/layout/item_grade_details.xml
  app/src/main/res/layout/item_license.xml
  app/src/main/res/layout/item_login_student_select.xml
  app/src/main/res/layout/item_mobile_device.xml
  app/src/main/res/layout/item_timetable.xml
  app/src/main/res/layout/item_timetable_small.xml
  app/src/main/res/layout/item_widget_timetable_dark.xml
  app/src/main/res/layout/item_widget_timetable_small.xml
  app/src/main/res/layout/item_widget_timetable_small_dark.xml
  app/src/main/res/layout/scrollable_header_about.xml
Labels: fix

#990 Reload grade list on mark all as read
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
Labels: fix, ux

#991 Cancel scheduled lesson notifications which turned into canceled
  app/src/main/java/io/github/wulkanowy/services/alarm/TimetableNotificationSchedulerHelper.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
Labels: fix, ux

#914 Add in-app updates support
  app/build.gradle
  app/src/fdroid/java/io/github/wulkanowy/utils/UpdateHelper.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/res/values/strings.xml
  app/src/play/java/io/github/wulkanowy/utils/UpdateHelper.kt
  build.gradle
Labels: new feature

#994 Add Vulcan and Scrapper Exceptions to known exceptions
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/utils/ResourcesExtension.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
  app/src/play/java/io/github/wulkanowy/utils/UpdateHelper.kt
Labels: enhancement, ux

#997 Make AppGallery badge background transparent.
  appgallery_badge.png
Labels: hotfix

#999 Fix grade header item object comparision
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
Labels: fix

#1003 Update hianalytics to 5.0.4.301
  app/build.gradle
Labels: dependencies
