Repository wulkanowy/wulkanowy, pull requests merged in 2020-04, with the labels that each got.

#750 Update gradle to 6.2.2
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies

#739 Add "System theme" option to widgets
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigureActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigureActivity.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: new feature

#741 Add better validation to login/email field
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
Labels: ux

#734 Add message attachments
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/24.json
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/MessageAttachmentDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/MessagesDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Message.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/MessageAttachment.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/MessageWithAttachment.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration24.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabView.kt
  app/src/main/res/drawable/ic_attachment.xml
  app/src/main/res/layout/fragment_message_preview.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/item_message_attachment.xml
  app/src/main/res/layout/item_message_divider.xml
  app/src/main/res/layout/item_message_preview.xml
  app/src/test/java/io/github/wulkanowy/data/repositories/message/MessageRepositoryTest.kt
Labels: db, feature request

#743 Add mark as done feature in homework
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/25.json
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/Converters.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Homework.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration25.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/homework/HomeworkLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/homework/HomeworkRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/homework/HomeworkRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/details/HomeworkDetailsDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/details/HomeworkDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/details/HomeworkDetailsView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainModule.kt
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/layout/dialog_homework.xml
  app/src/main/res/layout/item_homework.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/api_hosts.xml
  app/src/main/res/values/strings.xml
Labels: db, new feature

#751 Add more details in email template
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolView.kt
  app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt
  app/src/main/res/layout/fragment_login_symbol.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, ux

#752 Add missing sdk initialization in lucky number repository
  app/src/main/java/io/github/wulkanowy/data/repositories/luckynumber/LuckyNumberRepository.kt
Labels: fix

#643 Add force sync feature in settings
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/services/sync/SyncManager.kt
  app/src/main/java/io/github/wulkanowy/services/sync/SyncWorker.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsView.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences.xml
Labels: new feature, sync

#761 Use recycler view in homework details dialog
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/details/HomeworkDetailsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/details/HomeworkDetailsDialog.kt
  app/src/main/res/layout/dialog_homework.xml
  app/src/main/res/layout/item_homework_dialog_attachment.xml
  app/src/main/res/layout/item_homework_dialog_attachments_header.xml
  app/src/main/res/layout/item_homework_dialog_details.xml
Labels: fix

#762 Fix crash in message preview
  app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/LoggerUtils.kt
Labels: fix

#763 Fix crash caused by updating view in not attached fragment
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt
Labels: fix

#765 Fix homework dialog size
  app/src/main/res/layout/dialog_homework.xml
  app/src/main/res/layout/item_homework_dialog_details.xml
Labels: fix

#766 Show all known adfslight registers in register list
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverView.kt
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/layout/fragment_login_recover.xml
  app/src/main/res/values/api_hosts.xml
  app/src/main/res/values/api_symbols.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
Labels: enhancement, ux

#774 Fix visibility of dialog close button when homework content is long
  app/src/main/res/layout/dialog_homework.xml
  app/src/main/res/layout/item_homework_dialog_details.xml
Labels: fix, ux

#775 Don't log common errors to crashlytics
  app/src/main/java/io/github/wulkanowy/services/sync/SyncWorker.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessagePresenter.kt
  app/src/play/java/io/github/wulkanowy/utils/CrashlyticsUtils.kt
Labels: enhancement

#778 Add error message and bug report button to error dialog
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainModule.kt
  app/src/main/java/io/github/wulkanowy/utils/ResourcesExtension.kt
  app/src/main/res/layout/dialog_error.xml
  app/src/main/res/values-pl/strings.xml
Labels: enhancement

#777 Fix crash after send message when activity is in background
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessageActivity.kt
Labels: fix

#776 Refresh semesters if previous list was downloaded in different mode
  app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentLocal.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/semester/SemesterRepositoryTest.kt
Labels: fix

#780 Fix injector of ErrorDialog
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/di/BindingModule.kt
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainModule.kt
  app/src/main/java/io/github/wulkanowy/utils/ResourcesExtension.kt
  app/src/main/res/layout/dialog_error.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: fix
