Repository wulkanowy/wulkanowy, pull requests merged in 2020-01, with the labels that each got.

#634 Change grade header note to unread count
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsHeader.kt
  app/src/main/res/drawable/background_header_note.xml
  app/src/main/res/layout/header_grade_details.xml
Labels: ui, ux

#642 Add missing translations
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
Labels: fix

#645 Update error_service_unavailable string
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, ux

#637 Add debug notification icons
  app/src/debug/res/drawable-anydpi-v24/ic_stat_grade.xml
  app/src/debug/res/drawable-anydpi-v24/ic_stat_luckynumber.xml
  app/src/debug/res/drawable-anydpi-v24/ic_stat_message.xml
  app/src/debug/res/drawable-anydpi-v24/ic_stat_note.xml
  app/src/debug/res/drawable-hdpi/ic_stat_grade.png
  app/src/debug/res/drawable-hdpi/ic_stat_luckynumber.png
  app/src/debug/res/drawable-hdpi/ic_stat_message.png
  app/src/debug/res/drawable-hdpi/ic_stat_note.png
  app/src/debug/res/drawable-mdpi/ic_stat_grade.png
  app/src/debug/res/drawable-mdpi/ic_stat_luckynumber.png
  app/src/debug/res/drawable-mdpi/ic_stat_message.png
  app/src/debug/res/drawable-mdpi/ic_stat_note.png
  app/src/debug/res/drawable-xhdpi/ic_stat_grade.png
  app/src/debug/res/drawable-xhdpi/ic_stat_luckynumber.png
  app/src/debug/res/drawable-xhdpi/ic_stat_message.png
  app/src/debug/res/drawable-xhdpi/ic_stat_note.png
  app/src/debug/res/drawable-xxhdpi/ic_stat_grade.png
  app/src/debug/res/drawable-xxhdpi/ic_stat_luckynumber.png
  app/src/debug/res/drawable-xxhdpi/ic_stat_message.png
  app/src/debug/res/drawable-xxhdpi/ic_stat_note.png
  app/src/main/res/drawable-anydpi-v24/ic_stat_grade.xml
  app/src/main/res/drawable-anydpi-v24/ic_stat_luckynumber.xml
  app/src/main/res/drawable-anydpi-v24/ic_stat_message.xml
  app/src/main/res/drawable-anydpi-v24/ic_stat_note.xml
  app/src/main/res/drawable/ic_main_grade.xml
  app/src/main/res/drawable/ic_main_more.xml
Labels: enhancement

#631 Improve grades dialog layout
  app/jacoco.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsDialog.kt
  app/src/main/java/io/github/wulkanowy/utils/GradeExtension.kt
  app/src/main/res/layout/dialog_grade.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: new feature, ui

#652 Fix login info autofill
  app/src/main/res/layout/fragment_login_advanced.xml
  app/src/main/res/layout/fragment_login_form.xml
Labels: bug

#654 Add option to show only student plan lessons
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/20.json
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TestTimetableEntityCreator.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Timetable.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration20.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/timetable/TimetableRemote.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/res/layout/item_timetable_small.xml
  app/src/main/res/values-pl/preferences_values.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/preferences_values.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/preferences_values.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences.xml
Labels: new feature, ux

#636 Add creators list
  app/build.gradle
  app/src/main/assets/creators.json
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/pojos/AppCreator.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/appcreator/AppCreatorRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/creator/CreatorFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/creator/CreatorItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/creator/CreatorPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/creator/CreatorView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainModule.kt
  app/src/main/res/drawable/ic_about_creator.xml
  app/src/main/res/layout/fragment_creator.xml
  app/src/main/res/layout/item_creator.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: new feature

#533 Add excusing for absence
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/21.json
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/attendance/AttendanceLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TestTimetableEntityCreator.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Attendance.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration21.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/attendance/AttendanceRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/attendance/AttendanceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/attendance/SentExcuseStatus.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceModule.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainModule.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainView.kt
  app/src/main/res/drawable-night/background_header_note.xml
  app/src/main/res/drawable/background_header_note.xml
  app/src/main/res/drawable/ic_all_done.xml
  app/src/main/res/drawable/ic_all_done_all.xml
  app/src/main/res/drawable/ic_excuse_denied.xml
  app/src/main/res/drawable/ic_excuse_waiting.xml
  app/src/main/res/layout/dialog_excuse.xml
  app/src/main/res/layout/dialog_grade.xml
  app/src/main/res/layout/fragment_attendance.xml
  app/src/main/res/layout/header_grade_details.xml
  app/src/main/res/layout/item_attendance.xml
  app/src/main/res/menu/context_menu_excuse.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: hacktoberfest, new feature

#666 Don't hide password toggle button on error
  app/src/main/res/layout/fragment_login_advanced.xml
  app/src/main/res/layout/fragment_login_form.xml
Labels: fix, ux

#665 Visual enhancement of displaying grades point stats
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration20.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsLocal.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsPresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/NumberExtension.kt
Labels: enhancement, ux

#664 Show points sum in grades details
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsHeader.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt
  app/src/main/res/layout/fragment_attendance.xml
  app/src/main/res/layout/header_grade_details.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
Labels: new feature, ux

#668 Fix timetable_show_whole_class_entries en translation
  app/src/main/res/values/preferences_values.xml
Labels: fix, translation
