Repository wulkanowy/wulkanowy, pull requests merged in 2020-11, with the labels that each got.

#1004 Add conferences
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/28.json
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/ConferenceDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Conference.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration28.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/conference/ConferenceLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/conference/ConferenceRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/conference/ConferenceRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/conference/ConferenceAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/conference/ConferenceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/conference/ConferencePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/conference/ConferenceView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MorePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreView.kt
  app/src/main/res/drawable/ic_more_conferences.xml
  app/src/main/res/layout/fragment_conference.xml
  app/src/main/res/layout/item_conference.xml
  app/src/main/res/values/strings.xml
Labels: feature request

#1014 Change english strings
  app/src/main/res/values/preferences_values.xml
  app/src/main/res/values/strings.xml
Labels: translation

#1017 Add average in class grades statistics
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/29.json
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsLocalTest.kt
  app/src/hms/java/io/github/wulkanowy/utils/CrashLogUtils.kt
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/GradePartialStatisticsDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/GradeSemesterStatisticsDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/GradeStatisticsDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/GradePartialStatistics.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/GradeSemesterStatistics.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration29.kt
  app/src/main/java/io/github/wulkanowy/data/pojos/GradeStatisticsItem.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsRepository.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/GradeStatisticsWork.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsPresenter.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsRemoteTest.kt
Labels: new feature

#1020 Update contributor's username
  app/src/main/assets/contributors.json
Labels: fix

#1021 Add facebook link to about
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutView.kt
  app/src/main/res/drawable/ic_about_facebook.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: new feature
