Repository wulkanowy/wulkanowy, pull requests merged in 2020-08, with the labels that each got.

#915 Save semesters with students during registration
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/db/dao/SemesterDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Semester.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/StudentWithSemesters.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/SemesterMapper.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/StudentMapper.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/grade/GradeRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigurePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigurePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetProvider.kt
  app/src/main/java/io/github/wulkanowy/utils/SemesterExtension.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/student/StudentRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
  build.gradle
Labels: architecture

#916 Fix messages after 20.09 update
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/27.json
  app/src/androidTest/java/io/github/wulkanowy/data/db/migrations/Migration27Test.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/TestEntityCreator.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/grade/GradeRepositoryTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/luckynumber/LuckyNumberLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/recipient/RecipientLocalTest.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/MessagesDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Message.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Student.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration27.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/StudentMapper.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/contributor/ContributorPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabView.kt
  app/src/main/res/layout/item_message_preview.xml
  app/src/test/java/io/github/wulkanowy/TestEnityCreator.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/message/MessageRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
Labels: uonet-update

#927 Update dependencies
  app/build.gradle
Labels: dependencies
