Repository wulkanowy/wulkanowy, pull requests merged in 2020-02, with the labels that each got.

#674 Fix login more options button in dark theme
  app/src/main/res/layout/fragment_login_form.xml
Labels: bug, fix, ui

#672 Add total attendance summary
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryView.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
Labels: new feature

#677 Disable signed in students in login
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt
  app/src/main/res/layout/item_login_student_select.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
Labels: enhancement, ui, ux

#676 Add dynamic nick/email in login
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/res/layout/fragment_login_advanced.xml
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
Labels: enhancement, new feature, ui, ux

#678 Fix showing empty total summary and ordering of summary months
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryPresenter.kt
Labels: fix, ui, ux

#684 Show semester in appbar subtitle in grades view
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainView.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
Labels: ui, ux

#682 Refactor the resizing of the lucky number app widget
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetProvider.kt
Labels: ui

#687 Respect user settings in timetable app widget
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TestTimetableEntityCreator.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Timetable.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/timetable/TimetableRemote.kt
  app/src/main/java/io/github/wulkanowy/services/widgets/TimetableWidgetService.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
  app/src/main/res/layout/item_widget_timetable_small.xml
  app/src/main/res/layout/item_widget_timetable_small_dark.xml
Labels: new feature, ui, ux

#686 Add log viewer
  app/build.gradle
  app/src/fdroid/java/io/github/wulkanowy/utils/CrashlyticsUtils.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/logger/LoggerRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/logviewer/LogViewerAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/logviewer/LogViewerFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/logviewer/LogViewerPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/logviewer/LogViewerView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainModule.kt
  app/src/main/java/io/github/wulkanowy/utils/LoggerUtils.kt
  app/src/main/res/drawable/ic_refresh.xml
  app/src/main/res/layout/fragment_logviewer.xml
  app/src/main/res/menu/action_menu_logviewer.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/provider_paths.xml
  app/src/play/java/io/github/wulkanowy/utils/CrashlyticsUtils.kt
Labels: feature request

#681 Automatically switch semesters without sync
  app/build.gradle
  app/src/androidTest/java/io/github/wulkanowy/data/db/migrations/Migration13Test.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/attendance/AttendanceLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/completedlessons/CompletedLessonsLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/exam/ExamLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/grade/GradeLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/luckynumber/LuckyNumberLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TimetableLocalTest.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Semester.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradePresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/SemesterExtension.kt
  app/src/main/java/io/github/wulkanowy/utils/TimeExtension.kt
  app/src/main/res/layout/fragment_grade_statistics.xml
  app/src/test/java/io/github/wulkanowy/data/repositories/semester/SemesterRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/semester/TestSemesterEnityCreator.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
Labels: sync

#635 Add account recover
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/repositories/recover/RecoverRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/recover/RecoverRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginModule.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/RecoverErrorHandler.kt
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/layout/fragment_login_recover.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
Labels: new feature, ui

#689 Show list of charts in grade statistics
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsLocalTest.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/GradePointsStatisticsDao.kt
  app/src/main/java/io/github/wulkanowy/data/pojos/GradeStatisticsItem.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsView.kt
  app/src/main/java/io/github/wulkanowy/utils/NumberExtension.kt
  app/src/main/res/layout/fragment_grade_statistics.xml
  app/src/main/res/layout/item_grade_statistics_bar.xml
  app/src/main/res/layout/item_grade_statistics_pie.xml
Labels: ui, ux

#705 Update gradle to 6.2.1
  .travis.yml
  app/build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#704 Add separate host in login form to login to VULCAN adfslight
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverView.kt
  app/src/main/java/io/github/wulkanowy/utils/EditTextExtension.kt
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/layout/fragment_login_recover.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/api_hosts.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
Labels: ui, ux

#706 Sort the second group's lessons below the student's lessons
  .travis.yml
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
Labels: fix, ux
