Repository wulkanowy/wulkanowy, pull requests merged in 2020-03, with the labels that each got.

#711 Update Ukrainian language
  app/src/main/res/values-uk/strings.xml
Labels: fix, translation

#708 Filter lucky numbers by school shortcut
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/22.json
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/luckynumber/LuckyNumberLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/recipient/RecipientLocalTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/student/StudentLocalTest.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Student.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration22.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/luckynumber/LuckyNumberLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/luckynumber/LuckyNumberRemote.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/luckynumber/LuckyNumberRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentRemote.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/LuckyNumberWork.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetProvider.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/luckynumber/LuckyNumberRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/student/StudentRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
Labels: db

#710 Replace Maybe with Single in Message DAO
  app/src/androidTest/java/io/github/wulkanowy/data/repositories/grade/GradeRepositoryTest.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/MessagesDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageLocal.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRepository.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/UnitTestInternetObservingStrategy.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/message/MessageRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/student/StudentRemoteTest.kt
Labels: db

#707 Set missing styles to small lesson items
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableItem.kt
  app/src/main/res/layout/item_timetable_small.xml
  app/src/main/res/layout/item_widget_timetable_small.xml
  app/src/main/res/layout/item_widget_timetable_small_dark.xml
Labels: fix, ui, ux

#714 Change asset name and contributor name
  app/src/main/assets/contributors.json
  app/src/main/java/io/github/wulkanowy/data/repositories/appcreator/AppCreatorRepository.kt
Labels: enhancement

#716 Add some login help messages
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/res/layout/fragment_login_advanced.xml
  app/src/main/res/layout/fragment_login_recover.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, ui, ux

#719 Update gradle-publisher to 2.7.2
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/menu/action_menu_logviewer.xml
  build.gradle
Labels: dependencies

#722 Fix marking message as read in hybrid and mobile api mode
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/message/MessageRepositoryTest.kt
Labels: fix

#733 Bump chucker from 2.0.4 to 3.1.1
  app/build.gradle
  app/src/debug/res/values/preferences_defaults.xml
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/RecoverErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsErrorHandler.kt
Labels: dependencies

#736 Change strings.xml form from male to impersonal
  app/src/main/res/values-pl/strings.xml
Labels: translation

#738 Add points to notes
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/23.json
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Note.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration23.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/note/NoteRemote.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteItem.kt
  app/src/main/res/layout/dialog_note.xml
  app/src/main/res/layout/item_note.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: new feature

#737 Bump appcompat from 1.1.0 to 1.2.0-alpha03 to fix webview crash on api 21
  app/build.gradle
Labels: dependencies, fix
