Repository wulkanowy/wulkanowy, pull requests merged in 2021-02, with the labels that each got.

#1117 Replace progressBar with CircularProgressIndicator
  app/build.gradle
  app/src/main/res/layout/activity_send_message.xml
  app/src/main/res/layout/dialog_mobile_device.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_attendance.xml
  app/src/main/res/layout/fragment_attendance_summary.xml
  app/src/main/res/layout/fragment_conference.xml
  app/src/main/res/layout/fragment_contributor.xml
  app/src/main/res/layout/fragment_exam.xml
  app/src/main/res/layout/fragment_grade.xml
  app/src/main/res/layout/fragment_grade_details.xml
  app/src/main/res/layout/fragment_grade_statistics.xml
  app/src/main/res/layout/fragment_grade_summary.xml
  app/src/main/res/layout/fragment_homework.xml
  app/src/main/res/layout/fragment_license.xml
  app/src/main/res/layout/fragment_login_advanced.xml
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/layout/fragment_login_recover.xml
  app/src/main/res/layout/fragment_login_student_select.xml
  app/src/main/res/layout/fragment_login_symbol.xml
  app/src/main/res/layout/fragment_lucky_number.xml
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/layout/fragment_message_preview.xml
  app/src/main/res/layout/fragment_message_tab.xml
  app/src/main/res/layout/fragment_mobile_device.xml
  app/src/main/res/layout/fragment_note.xml
  app/src/main/res/layout/fragment_school.xml
  app/src/main/res/layout/fragment_schoolandteachers.xml
  app/src/main/res/layout/fragment_student_info.xml
  app/src/main/res/layout/fragment_teacher.xml
  app/src/main/res/layout/fragment_timetable.xml
  app/src/main/res/layout/fragment_timetable_additional.xml
  app/src/main/res/layout/fragment_timetable_completed.xml
Labels: enhancement

#1115 Change timetable icon
  app/src/debug/res/drawable-anydpi-v24/ic_stat_timetable.xml
  app/src/debug/res/drawable-hdpi/ic_stat_timetable.png
  app/src/debug/res/drawable-mdpi/ic_stat_timetable.png
  app/src/debug/res/drawable-xhdpi/ic_stat_timetable.png
  app/src/debug/res/drawable-xxhdpi/ic_stat_timetable.png
  app/src/main/res/drawable-anydpi-v24/ic_stat_timetable.xml
  app/src/main/res/drawable-hdpi/ic_stat_timetable.png
  app/src/main/res/drawable-mdpi/ic_stat_timetable.png
  app/src/main/res/drawable-xhdpi/ic_stat_timetable.png
  app/src/main/res/drawable-xxhdpi/ic_stat_timetable.png
  app/src/main/res/drawable/ic_main_timetable.xml
  app/src/main/res/drawable/ic_menu_timetable_lessons_additional.xml
Labels: ui

#1118 Add dark mode to swipe refresh layout
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/conference/ConferenceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDeviceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/school/SchoolFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/teacher/TeacherFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/studentinfo/StudentInfoFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/AdditionalLessonsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsFragment.kt
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: new feature

#1122 Fix empty messages after timeout bug
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
Labels: fix

#1124 Ignore webview exception
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
Labels: fix

#1125 Add final average grades calculation with modifiers
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryAdapter.kt
  app/src/main/java/io/github/wulkanowy/utils/GradeExtension.kt
  app/src/test/java/io/github/wulkanowy/utils/GradeExtensionTest.kt
Labels: new feature

#1128 Fix nullable student guardians
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/33.json
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/StudentInfo.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration33.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/StudentInfoMapper.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/studentinfo/StudentInfoFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/studentinfo/StudentInfoPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/studentinfo/StudentInfoView.kt
  app/src/main/res/layout/fragment_student_info.xml
  app/src/main/res/values/strings.xml
Labels: fix

#1140 Add checking vulcan average from both semesters
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProvider.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: fix

#1145 Fix EOF error in messages
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/34.json
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration34.kt
Labels: fix

#1120 Change background of navigation and notification bars
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/ui/base/ThemeManager.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values-v23/styles.xml
  app/src/main/res/values-v26/styles.xml
  app/src/main/res/values-v28/styles.xml
  app/src/main/res/values-v29/styles.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, ui

#1154 Add Slovak language to dialog
  app/src/main/res/values-cs-rCZ/preferences_values.xml
  app/src/main/res/values-de/preferences_values.xml
  app/src/main/res/values-pl/preferences_values.xml
  app/src/main/res/values-ru/preferences_values.xml
  app/src/main/res/values-sk-rSK/preferences_values.xml
  app/src/main/res/values-uk/preferences_values.xml
  app/src/main/res/values/preferences_values.xml
Labels: new feature
