Repository wulkanowy/wulkanowy, pull requests merged in 2021-07, with the labels that each got.

#1267 Add dashboard
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/ConferenceDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceSummaryRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/ConferenceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardAnnouncementsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardConferencesAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardExamsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardGradesAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardHomeworkAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MorePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreView.kt
  app/src/main/java/io/github/wulkanowy/utils/TimeExtension.kt
  app/src/main/res/drawable/ic_main_dashboard.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/item_dashboard_account.xml
  app/src/main/res/layout/item_dashboard_announcements.xml
  app/src/main/res/layout/item_dashboard_conferences.xml
  app/src/main/res/layout/item_dashboard_exams.xml
  app/src/main/res/layout/item_dashboard_grades.xml
  app/src/main/res/layout/item_dashboard_homework.xml
  app/src/main/res/layout/item_dashboard_horizontal_group.xml
  app/src/main/res/layout/item_dashboard_lessons.xml
  app/src/main/res/layout/subitem_dashboard_announcements.xml
  app/src/main/res/layout/subitem_dashboard_conferences.xml
  app/src/main/res/layout/subitem_dashboard_exams.xml
  app/src/main/res/layout/subitem_dashboard_grades.xml
  app/src/main/res/layout/subitem_dashboard_homework.xml
  app/src/main/res/layout/subitem_dashboard_small_grade.xml
  app/src/main/res/menu/action_menu_dashboard.xml
  app/src/main/res/values/api_hosts.xml
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/preferences_values.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences_appearance.xml
Labels: new feature

#1306 Add draft message
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/SharedPrefProvider.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Recipient.kt
  app/src/main/java/io/github/wulkanowy/data/pojos/MessageDraft.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/RecipientChipItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessageActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessagePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessageView.kt
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/data/repositories/MessageRepositoryTest.kt
Labels: new feature

#1413 Fix sorting notes in loading state
  .gitignore
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NotePresenter.kt
Labels: fix

#1414 Fix margin and attedance destination in dashboard
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt
  app/src/main/res/layout/item_dashboard_horizontal_group.xml
Labels: bug, ui
