Repository wulkanowy/wulkanowy, pull requests merged in 2021-11, with the labels that each got.

#1615 Allow selecting text in error dialog
  app/src/main/res/layout/dialog_error.xml
Labels: enhancement, fix

#1616 Notifications settings reorganize and strings update
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences_notifications.xml
Labels: enhancement, ux

#1601 Migrate from ViewPager to ViewPager2
  app/src/main/java/io/github/wulkanowy/ui/base/BaseFragmentPagerAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessagePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/SchoolAndTeachersFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/SchoolAndTeachersPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/widgets/SwipeDisabledViewPager.kt
  app/src/main/java/io/github/wulkanowy/utils/ViewPagerExtension.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_grade.xml
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/layout/fragment_schoolandteachers.xml
Labels: architecture

#1627 Fix homework sync
  app/src/main/java/io/github/wulkanowy/services/sync/works/HomeworkWork.kt
Labels: sync, fix

#1609 Do not show student's name in notifications if there's only one student
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/AppNotificationManager.kt
Labels: enhancement

#1632 Fix admin messages caching
  app/src/main/java/io/github/wulkanowy/data/repositories/AdminMessageRepository.kt
Labels: fix

#1599 Prevent changing the current day by accident when excusing absences
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceView.kt
  app/src/main/res/layout/fragment_attendance.xml
Labels: ux, fix

#1634 Add sorting to dashboard homework and grades
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
Labels: fix

#1641 Remove deprecated usage of LifecycleObserver
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/utils/LifecycleAwareVariable.kt
Labels: fix

#1633 Fix saved state in main and splash activity
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/services/alarm/TimetableNotificationReceiver.kt
  app/src/main/java/io/github/wulkanowy/services/shortcuts/ShortcutsHelper.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/ChangeTimetableNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewAttendanceNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewConferenceNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewExamNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewGradeNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewHomeworkNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewLuckyNumberNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewMessageNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewNoteNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewSchoolAnnouncementNotification.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BasePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetProvider.kt
Labels: fix

#1600 Fix displaying errors in GradeDetailsPresenter
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/school/SchoolPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/teacher/TeacherPresenter.kt
Labels: fix

#1644 School and teachers UI fixes
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageFragment.kt
  app/src/main/res/layout/fragment_school.xml
Labels: fix

#1645 Login improvements
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolView.kt
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: app-login

#1647 Add missing env for google play build
  .github/workflows/deploy-store.yml
Labels: ci

#1650 Fix upcoming lesson notifications on Android 12
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/services/alarm/TimetableNotificationSchedulerHelper.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsView.kt
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: fix

#1651 Add multiline to support ad preference
  app/src/play/res/xml/scheme_preferences_ads.xml
Labels: fix

#1664 Fix nul login data in login symbol view
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginActivity.kt
Labels: fix

#1663 Probably fix snackbar crash in grade statistics view
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsFragment.kt
Labels: fix

#1665 Disable personalized ads in single support advert
  app/src/play/java/io/github/wulkanowy/utils/AdsHelper.kt
Labels: fix

#1662 Add ads limit
  app/src/main/res/values/strings.xml
  app/src/play/java/io/github/wulkanowy/ui/modules/settings/ads/AdsFragment.kt
  app/src/play/java/io/github/wulkanowy/ui/modules/settings/ads/AdsPresenter.kt
  app/src/play/java/io/github/wulkanowy/ui/modules/settings/ads/AdsView.kt
Labels: enhancement

#1668 Fix empty student list in LoginStudentSelect view
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolPresenter.kt
Labels: fix

#1661 Add dismiss to admin message
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/44.json
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/AdminMessage.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration44.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
  app/src/main/res/layout/item_dashboard_admin_message.xml
Labels: new feature

#1681 Update viewpager2 library to fix duplicated menu bug
  app/build.gradle
Labels: fix

#1682 Fix snackbar crash in grade statistics view
  app/src/main/java/io/github/wulkanowy/utils/LoggerUtils.kt
  app/src/main/res/layout/fragment_grade_statistics.xml
Labels: fix

#1669 New Crowdin updates
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-sk/strings.xml
Labels: translation

#1672 Convert from a stringly typed grade color to enum GradeColorTheme
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration41.kt
  app/src/main/java/io/github/wulkanowy/data/enums/GradeColorTheme.kt
  app/src/main/java/io/github/wulkanowy/data/enums/GradeExpandMode.kt
  app/src/main/java/io/github/wulkanowy/data/enums/GradeSortingMode.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardGradesAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeExpandMode.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeSortingMode.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsView.kt
  app/src/main/java/io/github/wulkanowy/utils/GradeExtension.kt
  app/src/test/java/io/github/wulkanowy/utils/GradeExtensionTest.kt
Labels: enhancement
