Repository wulkanowy/wulkanowy, pull requests merged in 2021-08, with the labels that each got.

#1425 Add student nick-or-name to notification summary
  README.en.md
  README.md
  app/src/main/java/io/github/wulkanowy/data/pojos/Notification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/channels/LuckyNumberChannel.kt
  app/src/main/java/io/github/wulkanowy/services/sync/channels/NewConferencesChannel.kt
  app/src/main/java/io/github/wulkanowy/services/sync/channels/NewExamChannel.kt
  app/src/main/java/io/github/wulkanowy/services/sync/channels/NewGradesChannel.kt
  app/src/main/java/io/github/wulkanowy/services/sync/channels/NewHomeworkChannel.kt
  app/src/main/java/io/github/wulkanowy/services/sync/channels/NewMessagesChannel.kt
  app/src/main/java/io/github/wulkanowy/services/sync/channels/NewNotesChannel.kt
  app/src/main/java/io/github/wulkanowy/services/sync/channels/NewSchoolAnnouncementsChannel.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/BaseNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewConferenceNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewExamNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewGradeNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewHomeworkNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewLuckyNumberNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewMessageNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewNoteNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewSchoolAnnouncementNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NotificationType.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/ConferenceWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/ExamWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/GradeWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/HomeworkWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/LuckyNumberWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/MessageWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/NoteWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/SchoolAnnouncementWork.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/debug/notification/NotificationDebugPresenter.kt
Labels: ux

#1426 Change dashboard no data strings
  app/src/main/res/values/strings.xml
Labels: ux

#1427 Fix filter search bug
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
Labels: fix

#1415 Add drag and drop to dashboard
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardItemMoveCallback.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
  app/src/main/res/layout/item_dashboard_horizontal_group.xml
  app/src/main/res/layout/subitem_dashboard_grades.xml
  app/src/main/res/values/strings.xml
Labels: ui, new feature

#1436 Add last sync date in sync settings
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/services/sync/SyncWorker.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/sync/SyncFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/sync/SyncPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/sync/SyncView.kt
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1428 Fix buggy timers in timetable
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
Labels: fix

#1437 Add captions for averages from how many items have been counted
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryAdapter.kt
  app/src/main/res/layout/scrollable_header_grade_summary.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1430 Show information when the recipient has read the message
  app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewAdapter.kt
  app/src/main/res/layout/item_message_preview.xml
  app/src/main/res/values/strings.xml
Labels: new feature

#1447 Remove Zachowanie from all count of subjects
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryAdapter.kt
  app/src/main/res/values/strings.xml
Labels: fix

#1449 Remove lithuanian lang
  app/src/main/res/values-lt-v29/preferences_values.xml
  app/src/main/res/values-lt/preferences_values.xml
  app/src/main/res/values-lt/strings.xml
Labels: translation

#1450 Add missing dashboard section
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainView.kt
  app/src/main/java/io/github/wulkanowy/utils/FragmentExtension.kt
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/preferences_values.xml
Labels: fix

#1292 Exams and homework notification fixes
  app/src/main/java/io/github/wulkanowy/data/repositories/ExamRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/HomeworkRepository.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewConferenceNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewExamNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewHomeworkNotification.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/debug/notification/mock/conference.kt
  app/src/main/res/values/strings.xml
Labels: fix

#1435 Add in app review
  app/build.gradle
  app/src/fdroid/java/io/github/wulkanowy/utils/InAppReviewHelper.kt
  app/src/hms/java/io/github/wulkanowy/utils/InAppReviewHelper.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainView.kt
  app/src/play/java/io/github/wulkanowy/utils/InAppReviewHelper.kt
Labels: new feature

#1451 Change display name for MRmlik12
  app/src/main/assets/contributors.json
Labels: ui

#1452 Update readBy and unreadBy fields during message list fetch
  app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/MessageRepositoryTest.kt
Labels: fix

#1455 Hide keyboard on opening login host dropdown
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
Labels: enhancement, ux

#1456 Fix crash on opening date pickers during holidays
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/history/LuckyNumberHistoryFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/history/LuckyNumberHistoryPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
Labels: fix

#1429 Add excuse function to "not excusable" account
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessageActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessagePresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/AttendanceExtension.kt
  app/src/main/res/values/strings.xml
Labels: new feature

#1459 New Crowdin updates
  app/src/main/res/values-de/preferences_values.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
Labels: translation

#1460 Fix opening twitter link from about on android 11
  app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt
Labels: fix
