Repository wulkanowy/wulkanowy, pull requests merged in 2021-04, with the labels that each got.

#1266 Fix content visibility in login recovery
  app/build.gradle
  app/src/main/play/release-notes/pl-PL/default.txt
  app/src/main/res/layout/fragment_login_recover.xml
Labels: hotfix

#1232 Drop support for android 4.x
  app/build.gradle
  app/jacoco.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/AppCreatorRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/logviewer/LogViewerFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/accountedit/AccountEditPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/history/LuckyNumberHistoryAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/history/LuckyNumberHistoryFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/advanced/AdvancedView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetProvider.kt
  app/src/main/java/io/github/wulkanowy/utils/security/Scrambler.kt
  app/src/main/res/layout/fragment_logviewer.xml
  app/src/main/res/layout/fragment_mobile_device.xml
  app/src/main/res/layout/item_attendance.xml
  app/src/main/res/layout/widget_luckynumber_dark.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values-v21/styles.xml
  app/src/main/res/values/preferences_values.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/splash/SplashPresenterTest.kt
Labels: architecture

#1243 Add new notifications
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/36.json
  app/src/main/assets/contributors.json
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Exam.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Homework.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration36.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/ExamRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/HomeworkRepository.kt
  app/src/main/java/io/github/wulkanowy/services/ServicesModule.kt
  app/src/main/java/io/github/wulkanowy/services/sync/channels/NewExamChannel.kt
  app/src/main/java/io/github/wulkanowy/services/sync/channels/NewHomeworkChannel.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/ExamWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/HomeworkWork.kt
  app/src/main/res/values/strings.xml
Labels: new feature

#1269 Display day header from website in timetable
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/37.json
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/TimetableHeaderDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/TimetableHeader.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration37.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/TimetableMapper.kt
  app/src/main/java/io/github/wulkanowy/data/pojos/TimetableFull.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/TimetableRepository.kt
  app/src/main/java/io/github/wulkanowy/services/alarm/TimetableNotificationSchedulerHelper.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/AdditionalLessonsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
  app/src/main/res/layout/fragment_timetable.xml
  app/src/main/res/layout/item_timetable.xml
  app/src/test/java/io/github/wulkanowy/data/repositories/TimetableRepositoryTest.kt
Labels: new feature

#1272 Cleanup github workflows
  .github/workflows/deploy-store.yml
  .github/workflows/deploy-test.yml
  .github/workflows/test.yml
  app/bitrise.jks
Labels: ci

#1271 Add system settings shortcut
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsView.kt
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences_notifications.xml
Labels: new feature

#1275 Ignore all throwable from WebView
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
Labels: fix

#1279 Student info and Teachers screens unification
  app/src/main/res/layout/item_student_info.xml
  app/src/main/res/layout/item_teacher.xml
Labels: ui

#1227 Dialogs adjustments to meet MD rules
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/token/MobileDeviceTokenDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonDialog.kt
  app/src/main/res/layout/dialog_attendance.xml
  app/src/main/res/layout/dialog_error.xml
  app/src/main/res/layout/dialog_exam.xml
  app/src/main/res/layout/dialog_grade.xml
  app/src/main/res/layout/dialog_homework.xml
  app/src/main/res/layout/dialog_lesson_completed.xml
  app/src/main/res/layout/dialog_mobile_device.xml
  app/src/main/res/layout/dialog_note.xml
  app/src/main/res/layout/dialog_timetable.xml
  app/src/main/res/layout/item_homework_dialog_attachment.xml
  app/src/main/res/layout/item_homework_dialog_attachments_header.xml
  app/src/main/res/layout/item_homework_dialog_details.xml
  app/src/main/res/values/colors.xml
Labels: ui

#1295 Update github action workflow
  .github/workflows/deploy-store.yml
  .github/workflows/deploy-test.yml
  .github/workflows/test.yml
  app/bitrise.jks
  app/build.gradle
  build.gradle
Labels: ci

#1291 Fix all year average
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeSubject.kt
  app/src/main/play/release-notes/pl-PL/default.txt
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
Labels: fix

#1297 Fix Homework dialog buttons layout
  app/src/main/res/layout/dialog_homework.xml
  app/src/main/res/layout/dialog_mobile_device.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
Labels: fix
