Repository wulkanowy/wulkanowy, pull requests merged in 2021-01, with the labels that each got.

#1064 Use Firebase Android BoM
  app/build.gradle
Labels: dependencies

#1069 Use work-gcm dependency in play flavor only
  app/build.gradle
Labels: dependencies

#1071 Disable force dark theme on Android >9
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/styles.xml
Labels: fix, ui

#1070 Handle URLs from FCM push notification
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashView.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/splash/SplashPresenterTest.kt
Labels: new feature

#1068 Auto-refresh displayed data after some time
  app/src/androidTest/java/io/github/wulkanowy/data/db/migrations/AbstractMigrationTest.kt
  app/src/main/java/io/github/wulkanowy/data/db/SharedPrefProvider.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/CompletedLessonsDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceSummaryRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/CompletedLessonsRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/ConferenceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/ExamRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/GradeRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/GradeStatisticsRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/HomeworkRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/MobileDeviceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/NoteRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/TimetableRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/conference/ConferenceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/conference/ConferencePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/conference/ConferenceView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDeviceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDevicePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDeviceView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NotePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsView.kt
  app/src/main/java/io/github/wulkanowy/utils/FlowUtils.kt
  app/src/main/java/io/github/wulkanowy/utils/RefreshUtils.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/AttendanceRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/CompletedLessonsRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/ExamRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/GradeRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/GradeStatisticsRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/MessageRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/MobileDeviceRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/TimetableRepositoryTest.kt
Labels: enhancement, sync, ux

#1076 Use userLoginId to differentiate saved mobiles devices between accounts
  app/src/main/java/io/github/wulkanowy/data/db/dao/MobileDeviceDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/MobileDevice.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/MobileDeviceMapper.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/MobileDeviceRepository.kt
Labels: fix

#1075 Use senderId to differentiate saved recipients between accounts
  app/src/main/java/io/github/wulkanowy/data/db/dao/RecipientDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Recipient.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/ReportingUnit.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/RecipientMapper.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/ReportingUnitMapper.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/RecipientRepository.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/RecipientWork.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessagePresenter.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/RecipientLocalTest.kt
Labels: fix

#1083 Show appropriate message when message does not exist
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewView.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/strings.xml
Labels: new feature

#1089 Fix google play deploy config
  .github/workflows/test.yml
  app/build.gradle
Labels: hotfix

#1092 Make strings in grade class stats translatable
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsPresenter.kt
  app/src/main/res/values/strings.xml
Labels: translation, ui

#1091 Fix translations of month name in attendance summary
  app/src/main/java/io/github/wulkanowy/utils/TimeExtension.kt
  app/src/test/java/io/github/wulkanowy/utils/TimeExtensionTest.kt
Labels: fix, ui

#1097 Fix selected semester after change account
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradePresenter.kt
Labels: fix

#1108 Update gradle and build tools
  app/build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#1105 Fix null data in Status.SUCCESS in emission from average provider
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeSubject.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/GradeExtension.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
Labels: fix

#1114 Add build date to version info
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutFragment.kt
  app/src/main/java/io/github/wulkanowy/utils/AppInfo.kt
Labels: feature request, ux

#1051 Update auto update priority policy
  app/src/play/java/io/github/wulkanowy/utils/UpdateHelper.kt
Labels: enhancement

#1113 Fix follow system language setting
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsView.kt
  app/src/play/java/io/github/wulkanowy/utils/AnalyticsHelper.kt
Labels: fix
