Repository wulkanowy/wulkanowy, pull requests merged in 2021-05, with the labels that each got.

#1270 Probably fix list divider color
  app/src/main/java/io/github/wulkanowy/ui/widgets/DividerItemDecoration.kt
  app/src/main/res/drawable-night/ic_all_divider.xml
  app/src/main/res/drawable/ic_all_divider.xml
  app/src/main/res/layout/dialog_error.xml
  app/src/main/res/layout/dialog_homework.xml
  app/src/main/res/layout/item_attendance_summary.xml
  app/src/main/res/layout/item_grade_summary.xml
Labels: fix

#1121 Change titles in Student Info
  app/src/main/java/io/github/wulkanowy/ui/modules/studentinfo/StudentInfoFragment.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, ui

#1322 Fix homework dialog attachments margin
  app/src/main/res/layout/item_homework_dialog_attachment.xml
  app/src/main/res/layout/item_homework_dialog_attachments_header.xml
Labels: fix

#1325 Fix missing snackbar in sync settings fragment
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: fix

#1323 Add school announcements
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/38.json
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/SchoolAnnouncementDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/SchoolAnnouncement.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration36.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration38.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/DirectorInformationMapper.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SchoolAnnouncementRepository.kt
  app/src/main/java/io/github/wulkanowy/services/ServicesModule.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/SchoolAnnouncementWork.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MorePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementView.kt
  app/src/main/res/layout/fragment_school_announcement.xml
  app/src/main/res/layout/item_school_announcement.xml
  app/src/main/res/values/strings.xml
Labels: new feature

#1324 Change mobile devices item order
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MorePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreView.kt
Labels: ui

#1276 Add notification icons
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/services/sync/SyncWorker.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/ExamWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/GradeWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/HomeworkWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/LuckyNumberWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/MessageWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/NoteWork.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutFragment.kt
  app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt
  app/src/main/res/drawable-hdpi/ic_stat_all.png
  app/src/main/res/drawable-mdpi/ic_stat_all.png
  app/src/main/res/drawable-xhdpi/ic_stat_all.png
  app/src/main/res/drawable-xxhdpi/ic_stat_all.png
  app/src/main/res/drawable-xxxhdpi/ic_stat_all.png
Labels: enhancement

#1327 Fix no info text position in school announcements
  app/src/main/res/layout/fragment_school_announcement.xml
Labels: bug, ui

#1338 Add arrows to student family list items
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/studentinfo/StudentInfoAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/studentinfo/StudentInfoFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/studentinfo/StudentInfoItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/studentinfo/StudentInfoPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/studentinfo/StudentInfoView.kt
  app/src/main/res/layout/fragment_student_info.xml
  app/src/main/res/layout/item_student_info.xml
Labels: enhancement

#1353 Update dependabot config
  .github/dependabot.yml
Labels: dependencies

#1354 Fix message sending and timetable changes parsing
  .github/workflows/deploy-store.yml
  .gitignore
  app/build.gradle
  app/src/main/play/release-notes/pl-PL/default.txt
  build.gradle
Labels: hotfix, uonet-update
