Repository wulkanowy/wulkanowy, pull requests merged in 2021-12, with the labels that each got.

#1717 Fix grade sorting by date
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
Labels: fix

#1689 Fix invalid order of school announcements
  app/src/main/java/io/github/wulkanowy/data/db/dao/SchoolAnnouncementDao.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementPresenter.kt
Labels: fix

#1724 Update template of login issue email
  app/build.gradle
  app/src/main/res/values/strings.xml
Labels: app-login

#1551 Update timetable to next day if there is no more lessons today
  .idea/codeStyles/Project.xml
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetProvider.kt
Labels: enhancement

#1686 Replace view pager in login activity with simple fragment transactions
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginData.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/RecoverErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/advanced/AdvancedFragment.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_login_recover.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/login/LoginPresenterTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
Labels: architecture

#1723 Fix that an incorrect day would be selected in MaterialDatePicker
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/add/HomeworkAddDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/add/HomeworkAddView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/history/LuckyNumberHistoryFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/history/LuckyNumberHistoryView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/AdditionalLessonsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/AdditionalLessonsView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/add/AdditionalLessonAddDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsView.kt
  app/src/main/java/io/github/wulkanowy/utils/MaterialDatePickerUtils.kt
  app/src/main/java/io/github/wulkanowy/utils/SchooldaysValidator.kt
  app/src/main/java/io/github/wulkanowy/utils/TimeExtension.kt
  app/src/test/java/io/github/wulkanowy/utils/TimeExtensionTest.kt
Labels: fix

#1716 Add option to remove notifications captured from vulcan.hebe
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/services/piggyback/VulcanNotificationListenerService.kt
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences_notifications.xml
Labels: new feature

#1708 Fix overlapping text in the error dialog
  app/src/main/java/io/github/wulkanowy/services/sync/SyncWorker.kt
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/sync/SyncFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/sync/SyncPresenter.kt
  app/src/main/res/layout/dialog_error.xml
Labels: ui, fix

#1735 Remove admin message offline first cache
  app/src/main/java/io/github/wulkanowy/data/repositories/AdminMessageRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
Labels: enhancement

#1715 Fix notification spam after login
  app/src/main/java/io/github/wulkanowy/services/sync/SyncManager.kt
  app/src/main/java/io/github/wulkanowy/services/sync/SyncWorker.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/AttendanceSummaryWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/AttendanceWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/CompletedLessonWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/ConferenceWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/ExamWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/GradeStatisticsWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/GradeWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/HomeworkWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/LuckyNumberWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/MessageWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/NoteWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/RecipientWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/SchoolAnnouncementWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/TeacherWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/TimetableWork.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/Work.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
Labels: ux, fix

#1711 If only one student exists, don't show student name in timetable notification
  app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/services/alarm/TimetableNotificationReceiver.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/AppNotificationManager.kt
Labels: ux

#1737 Fix timetable widget crash when there are no lessons for the day
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
Labels: fix

#1740 Fix play flavor build
  app/src/play/java/io/github/wulkanowy/services/messaging/AppMessagingService.kt
Labels: fix

#1738 Add basic support for kindergarten students
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/47.json
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Semester.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/SemesterMapper.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceSummaryRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/CompletedLessonsRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/ConferenceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/ExamRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/GradeRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/GradeStatisticsRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/HomeworkRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/MobileDeviceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/NoteRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SchoolRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SemesterRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentInfoRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SubjectRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/TeacherRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/TimetableRepository.kt
  app/src/test/java/io/github/wulkanowy/TestEnityCreator.kt
  app/src/test/java/io/github/wulkanowy/data/db/migrations/Migration13Test.kt
Labels: db, sync, new feature

#1741 Display comment after entry in grade notifications
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewGradeNotification.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/debug/notification/mock/gradeDetails.kt
Labels: enhancement, ux
