Repository wulkanowy/wulkanowy, pull requests merged in 2021-10, with the labels that each got.

#1555 Add Czech and Slovak listings
  app/src/main/play/listings/cs-CZ/full-description.txt
  app/src/main/play/listings/cs-CZ/short-description.txt
  app/src/main/play/listings/cs-CZ/title.txt
  app/src/main/play/listings/sk/full-description.txt
  app/src/main/play/listings/sk/short-description.txt
  app/src/main/play/listings/sk/title.txt
Labels: translation

#1554 Add presenter coroutines scope
  app/src/main/java/io/github/wulkanowy/ui/base/BasePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/debug/notification/NotificationDebugPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessagePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessagePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDevicePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NotePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/SchoolAndTeachersPresenter.kt
Labels: architecture, hacktoberfest

#1556 Set buildTimestamp through manifest meta
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/utils/AppInfo.kt
  app/src/test/java/io/github/wulkanowy/data/db/migrations/AbstractMigrationTest.kt
  app/src/test/java/io/github/wulkanowy/data/db/migrations/Migration35Test.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/StudentTest.kt
Labels: enhancement, ci, hacktoberfest

#1546 Change text to bold in notifications center
  app/src/main/res/layout/item_notifications_center.xml
Labels: ui

#1557 Migrate from moshi to kotlinx serialization
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/Converters.kt
  app/src/main/java/io/github/wulkanowy/data/db/adapters/PairAdapterFactory.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Recipient.kt
  app/src/main/java/io/github/wulkanowy/data/pojos/Contributor.kt
  app/src/main/java/io/github/wulkanowy/data/pojos/MessageDraft.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/AppCreatorRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/RecipientChipItem.kt
  app/src/test/java/io/github/wulkanowy/data/db/ConvertersTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/MessageRepositoryTest.kt
  build.gradle
Labels: hacktoberfest, dependencies

#1577 Error messages content wrap in error dialog
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorDialog.kt
  app/src/main/res/layout/dialog_error.xml
Labels: ui, ux
