Repository wulkanowy/wulkanowy, pull requests merged in 2021-03, with the labels that each got.

#1168 Add exception ignoring to UpdateHelper when PendingIntent is duplicated
  app/src/play/java/io/github/wulkanowy/utils/UpdateHelper.kt
Labels: fix

#1169 Fix calling of binding outside lifecycle
  app/src/main/java/io/github/wulkanowy/utils/LifecycleAwareVariable.kt
Labels: fix

#1170 Remove deprecations
  app/src/main/java/io/github/wulkanowy/ui/base/BaseFragmentPagerAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/details/HomeworkDetailsDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/token/MobileDeviceTokenDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonDialog.kt
Labels: enhancement

#1146 Add avatars
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/35.json
  app/src/androidTest/java/io/github/wulkanowy/data/db/migrations/AbstractMigrationTest.kt
  app/src/androidTest/java/io/github/wulkanowy/data/db/migrations/Migration35Test.kt
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Message.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Student.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/StudentNickAndAvatar.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration35.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/MessageMapper.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/StudentMapper.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/accountdetails/AccountDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/accountdetails/AccountDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/accountedit/AccountEditColorAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/accountedit/AccountEditDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/accountedit/AccountEditPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/accountedit/AccountEditView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/accountquick/AccountQuickDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/accountquick/AccountQuickPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainView.kt
  app/src/main/java/io/github/wulkanowy/utils/AppInfo.kt
  app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt
  app/src/main/res/drawable/ic_all_round_check.xml
  app/src/main/res/layout/dialog_account_edit.xml
  app/src/main/res/layout/dialog_account_quick.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_account_details.xml
  app/src/main/res/layout/item_account.xml
  app/src/main/res/layout/item_account_edit_color.xml
  app/src/main/res/layout/item_grade_statistics_pie.xml
  app/src/main/res/menu/action_menu_main.xml
  app/src/test/java/io/github/wulkanowy/data/repositories/StudentTest.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: new feature

#1178 Fix no system theme option in Czech and Slovak
  app/src/main/res/values-cs-rCZ-v29/preferences_values.xml
  app/src/main/res/values-sk-rSK-v29/preferences_values.xml
Labels: fix, ui

#1177 Remove hardcoded strings
  app/src/main/res/layout/dialog_account_edit.xml
  app/src/main/res/values/strings.xml
Labels: ui

#1176 Add early validation for special mail domains (#1000)
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
Labels: enhancement, ui

#1181 Fix API host key capitalisation for powiat krasnostawski
  app/src/main/res/values/api_hosts.xml
Labels: ui

#1182 Fix empty license dialog
  app/src/main/java/io/github/wulkanowy/ui/modules/about/license/LicenseFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/about/license/LicenseView.kt
  build.gradle
Labels: fix

#1185 Fix grade fragment subtitle
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/accountdetails/AccountDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeFragment.kt
Labels: fix

#1191 Migrate database migrations from androidTest to roboelectric
  .github/workflows/test.yml
  app/build.gradle
  app/src/test/java/io/github/wulkanowy/data/db/migrations/AbstractMigrationTest.kt
  app/src/test/java/io/github/wulkanowy/data/db/migrations/Migration12Test.kt
  app/src/test/java/io/github/wulkanowy/data/db/migrations/Migration13Test.kt
  app/src/test/java/io/github/wulkanowy/data/db/migrations/Migration27Test.kt
  app/src/test/java/io/github/wulkanowy/data/db/migrations/Migration35Test.kt
Labels: ci

#1192 Fix OOM in grade statistics
  app/src/main/java/io/github/wulkanowy/data/mappers/GradeStatisticsMapper.kt
  app/src/main/java/io/github/wulkanowy/data/pojos/GradeStatisticsItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/ViewType.kt
  app/src/main/res/layout/fragment_grade_statistics.xml
  app/src/main/res/layout/item_grade_statistics_header.xml
Labels: fix

#1160 Settings revamp
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MorePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/advanced/AdvancedFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/advanced/AdvancedPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/advanced/AdvancedView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/AppearanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/AppearancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/AppearanceView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/sync/SyncFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/sync/SyncPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/sync/SyncView.kt
  app/src/main/res/drawable/ic_all_about.xml
  app/src/main/res/drawable/ic_settings_advanced.xml
  app/src/main/res/drawable/ic_settings_appearance.xml
  app/src/main/res/drawable/ic_settings_notifications.xml
  app/src/main/res/drawable/ic_settings_sync.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences.xml
  app/src/main/res/xml/scheme_preferences_advanced.xml
  app/src/main/res/xml/scheme_preferences_appearance.xml
  app/src/main/res/xml/scheme_preferences_notifications.xml
  app/src/main/res/xml/scheme_preferences_sync.xml
Labels: enhancement, ui

#1194 Fix date picker theme
  app/src/main/res/values/styles.xml
Labels: fix

#1196 Fix notification and status bars colors
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/colors.xml
Labels: fix

#1197 Fix duplicate items after running automatic and manual sync at the same time
  app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceSummaryRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/CompletedLessonsRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/ConferenceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/ExamRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/GradeRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/GradeStatisticsRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/HomeworkRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/LuckyNumberRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/MobileDeviceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/NoteRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SchoolRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentInfoRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SubjectRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/TeacherRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/TimetableRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentRemote.kt
  app/src/main/java/io/github/wulkanowy/utils/FlowUtils.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/AttendanceRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/CompletedLessonsRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/ExamRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/GradeRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/LuckyNumberRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/MobileDeviceRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/utils/FlowUtilsKtTest.kt
Labels: architecture, sync

#1203 Replace dash mark with no data string in SchoolFragment
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/school/SchoolFragment.kt
Labels: enhancement

#1210 Ignore no current student during avatar loading
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
Labels: fix

#1211 Update kotlin coroutines
  app/build.gradle
Labels: dependencies

#1212 Change the absence request confirmation message string
  app/src/main/res/values/strings.xml
Labels: ui

#1213 Fix and clean proguard/r8 file
  app/build.gradle
  app/proguard-rules.pro
Labels: fix

#1214 Update material chips input
  app/build.gradle
Labels: dependencies

#1216 Maybe fix fragment commits after activity state is saved
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
Labels: fix

#1217 Fix empty view in attendance
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
Labels: fix

#1220 Add github actions config to deploy apk to App Center
  .github/workflows/test.yml
  app/bitrise.jks
  app/bitrise.jks.gpg
Labels: ci

#1215 Fix semester switch when student have only one semester
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeView.kt
Labels: fix

#1225 Fix show error details button in additional lessons
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/AdditionalLessonsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/AdditionalLessonsPresenter.kt
Labels: fix

#1226 Fix bugs in r8 and grade fragment
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradePresenter.kt
Labels: fix

#1235 Remove firebase in app messaging dependency
  app/build.gradle
Labels: dependencies

#1237 Remove listenablefuture from dependencies
  app/build.gradle
Labels: dependencies, fix

#1231 Fix very rare crash in login recovery
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverFragment.kt
  app/src/main/res/layout/fragment_login_recover.xml
Labels: fix

#1238 Fix missing avatars in widgets
  app/src/main/java/io/github/wulkanowy/ui/base/WidgetConfigureAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetProvider.kt
Labels: fix

#1241 Fix colorPrimary and class name in widget account manager
  app/src/main/java/io/github/wulkanowy/ui/base/WidgetConfigureAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigureActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigurePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigureView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigureActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigurePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigureView.kt
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/styles.xml
Labels: fix

#1254 Use db student id to distinguish reporting units and recipients
  app/src/main/java/io/github/wulkanowy/data/db/dao/RecipientDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Recipient.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/RecipientMapper.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/ReportingUnitMapper.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/RecipientRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/ReportingUnitRepository.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/RecipientLocalTest.kt
Labels: db, fix

#1242 Fix clearing no existing dialog fragment
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
Labels: fix

#1258 Allow special login format in login form
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
Labels: hotfix

#1259 Add deploy to AppGallery github actions config
  .github/workflows/test.yml
  app/build.gradle
  build.gradle
Labels: ci
