Repository wulkanowy/wulkanowy, pull requests merged in 2021-09, with the labels that each got.

#1469 Update agp
  build.gradle
Labels: dependencies

#1472 Fix showing error view in timetable
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
Labels: fix

#1470 Add missing school announcement dialog
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/res/layout/dialog_school_announcement.xml
Labels: ux

#1473 Fix preview of second student guardian when first guardian is null
  app/src/main/java/io/github/wulkanowy/ui/modules/studentinfo/StudentInfoAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/studentinfo/StudentInfoFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/studentinfo/StudentInfoItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/studentinfo/StudentInfoPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/studentinfo/StudentInfoView.kt
Labels: fix

#1475 Fix overlaping empty and error view in grade statistics
  app/src/main/res/layout/fragment_grade_statistics.xml
Labels: fix

#1474 New Crowdin updates
  app/src/main/res/values-pl/strings.xml
Labels: translation

#1463 Dashboard fixes
  app/src/main/java/io/github/wulkanowy/data/repositories/GradeRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SemesterRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BasePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/accountdetails/AccountDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/accountdetails/AccountDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/TimetableExtension.kt
  app/src/main/res/layout/item_dashboard_horizontal_group.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/utils/TimetableExtensionTest.kt
Labels: fix

#1483 Change AppGallery deploy format to aab
  .github/workflows/deploy-store.yml
  app/build.gradle
Labels: ci

#1495 Update material chips input
  app/build.gradle
Labels: dependencies

#1494 Fix overlapping shadow in dashboard
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardAdapter.kt
Labels: fix

#1498 Fix NPE in timetable dashboard tile
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardAdapter.kt
Labels: fix

#1493 Fix overlapping error view
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
Labels: fix

#1492 Fix error view in attendance summary
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryPresenter.kt
Labels: fix

#1500 Fix crash in school info when dialer is unavailable
  app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt
Labels: fix

#1501 Fix empty excuse list
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
Labels: fix

#1504 Restore lucky number in more view
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MorePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreView.kt
Labels: enhancement

#1502 Fix date picker crash after saved state
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/history/LuckyNumberHistoryFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/AdditionalLessonsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/completed/CompletedLessonsFragment.kt
Labels: fix

#1507 Update help email pre-filled content
  app/src/main/res/values/strings.xml
Labels: enhancement, app-login

#1506 Unlock sunday in navigation datepicker
  app/src/main/java/io/github/wulkanowy/utils/SchooldaysValidator.kt
Labels: enhancement

#1505 Fix login process after was interrupted
  app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/StudentTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
Labels: fix

#1517 Fix bugs in dashboard
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/res/layout/subitem_dashboard_grades.xml
Labels: fix

#1518 Fix ghost account after logout not current student
  app/src/main/java/io/github/wulkanowy/ui/modules/account/accountdetails/AccountDetailsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/accountdetails/AccountDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/account/accountdetails/AccountDetailsView.kt
Labels: fix

#1521 Display info in timetable as-is when lesson has change flag
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableDialog.kt
Labels: ux

#1526 Upgrade Gradle Play Publisher to 3.6.0
  .github/workflows/deploy-store.yml
  app/build.gradle
  app/key.p12.gpg
  build.gradle
Labels: ci, dependencies

#1527 Always include all language resources in app bundle
  app/build.gradle
Labels: translation

#1525 Display bad credentials error in the message box above login form
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: ui, ux, app-login

#1529 Mark teacher with yellow when new and old are the same
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
Labels: ui, fix

#1530 Add transparency to lucky number widget
  app/src/main/res/drawable/background_luckynumber_widget.xml
  app/src/main/res/drawable/background_luckynumber_widget_dark.xml
Labels: enhancement, ui

#1503 Add notification piggyback
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/services/piggyback/VulcanNotificationListenerService.kt
  app/src/main/java/io/github/wulkanowy/services/sync/SyncManager.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsView.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences_notifications.xml
Labels: new feature

#1532 Don't stop loading the timetable when error occurs in upcoming lessons notification scheduling
  app/src/main/java/io/github/wulkanowy/services/alarm/TimetableNotificationSchedulerHelper.kt
Labels: bug, fix

#1379 Add calculated average help dialog
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewAdapter.kt
  app/src/main/java/io/github/wulkanowy/utils/GradeExtension.kt
  app/src/main/res/drawable/ic_help.xml
  app/src/main/res/layout/scrollable_header_grade_summary.xml
  app/src/main/res/values-pl/preferences_values.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/preferences_values.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/utils/GradeExtensionTest.kt
Labels: ux

#1538 Fix hiding last element in messages
  app/src/main/res/layout/fragment_message_tab.xml
Labels: ui, fix

#1524 Add notification center
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/40.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/wulkanowy/data/RepositoryModule.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/NotificationDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Notification.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration40.kt
  app/src/main/java/io/github/wulkanowy/data/pojos/NotificationData.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/NotificationRepository.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/AppNotificationManager.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/BaseNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewConferenceNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewExamNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewGradeNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewHomeworkNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewLuckyNumberNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewMessageNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewNoteNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewSchoolAnnouncementNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NotificationType.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/AttendanceWork.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/debug/notification/NotificationDebugPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/notificationscenter/NotificationsCenterAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/notificationscenter/NotificationsCenterFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/notificationscenter/NotificationsCenterPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/notificationscenter/NotificationsCenterView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsFragment.kt
  app/src/main/res/layout/fragment_notifications_center.xml
  app/src/main/res/layout/item_notifications_center.xml
  app/src/main/res/menu/action_menu_dashboard.xml
  app/src/main/res/menu/action_menu_main.xml
  app/src/main/res/values/strings.xml
  app/src/play/java/io/github/wulkanowy/services/messaging/AppMessagingService.kt
Labels: new feature

#1539 Remove seconds from timetable timer
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt
Labels: enhancement

#1537 Add option to make upcoming lesson notification not persistent
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/services/alarm/TimetableNotificationReceiver.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsPresenter.kt
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences_notifications.xml
Labels: enhancement

#1540 Add missing auto refresh to recipients, subjects and teachers
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceSummaryRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/CompletedLessonsRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/ConferenceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/ExamRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/GradeRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/GradeStatisticsRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/HomeworkRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/LuckyNumberRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/MobileDeviceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/NoteRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/NotificationRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/RecipientRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/RecoverRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SchoolAnnouncementRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SchoolRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentInfoRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SubjectRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/TeacherRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/TimetableRepository.kt
  app/src/main/java/io/github/wulkanowy/utils/RefreshUtils.kt
  app/src/main/res/values/api_hosts.xml
  app/src/test/java/io/github/wulkanowy/data/repositories/AttendanceRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/CompletedLessonsRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/ExamRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/GradeRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/GradeStatisticsRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/MessageRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/MobileDeviceRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/RecipientLocalTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/TimetableRepositoryTest.kt
Labels: sync

#1545 Remove disappearing teachers workaround from timetable repository
  app/src/main/java/io/github/wulkanowy/data/repositories/TimetableRepository.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/TimetableRepositoryTest.kt
Labels: db, sync

#1544 New Crowdin updates
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
Labels: translation
