Repository wulkanowy/wulkanowy, pull requests merged in 2022-10, with the labels that each got.

#2000 Reorder action buttons on the message preview screen to hide the forward button in overflow menu
  app/src/main/res/menu/action_menu_message_preview.xml
Labels: enhancement, ux

#2009 Fix grade weight text truncation in grade dialog with large font set
  app/src/main/res/layout/dialog_grade.xml
Labels: fix

#2027 Use text color, font face and red dot to differentiate unread messages
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabAdapter.kt
  app/src/main/res/drawable/ic_circle.xml
  app/src/main/res/layout/item_message.xml
Labels: enhancement, ui, ux

#2028 Fix SSL certificate out-of-date detection
  app/src/main/java/io/github/wulkanowy/utils/ExceptionExtension.kt
Labels: ux
