Repository wulkanowy/wulkanowy, pull requests merged in 2022-06, with the labels that each got.

#1887 Update dependencies
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  build.gradle
Labels: dependencies

#1894 Fix case sensitive domain checker
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
Labels: fix

#1893 Fix date in attendance and timetable when day is changing
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
Labels: fix

#1892 Fix typo in average description
  app/src/main/res/values/strings.xml
Labels: fix

#1891 Fix multiline address in student info
  app/src/main/res/layout/fragment_student_info.xml
  app/src/main/res/layout/item_student_info.xml
Labels: fix

#1898 Fix jumping points in notes on refresh
  app/src/main/res/layout/fragment_note.xml
  app/src/main/res/layout/item_note.xml
Labels: fix

#1897 Fix doubled and no announcements
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/49.json
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/SchoolAnnouncementDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/SchoolAnnouncement.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration49.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/DirectorInformationMapper.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SchoolAnnouncementRepository.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/SchoolAnnouncementWork.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/debug/notification/mock/schoolAnnouncement.kt
Labels: fix

#1862 Fix timetable widget day reset
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigureActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetProvider.kt
Labels: fix

#1815 Add ads to dashboard
  app/build.gradle
  app/src/fdroid/java/io/github/wulkanowy/utils/AdsHelper.kt
  app/src/hms/java/io/github/wulkanowy/utils/AdsHelper.kt
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardItemMoveCallback.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/adapters/DashboardAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/adapters/DashboardAnnouncementsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/adapters/DashboardConferencesAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/adapters/DashboardExamsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/adapters/DashboardGradesAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/adapters/DashboardHomeworkAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainView.kt
  app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt
  app/src/main/res/layout/dialog_ads_consent.xml
  app/src/main/res/layout/item_dashboard_ads.xml
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/play/java/io/github/wulkanowy/ui/modules/settings/ads/AdsFragment.kt
  app/src/play/java/io/github/wulkanowy/ui/modules/settings/ads/AdsPresenter.kt
  app/src/play/java/io/github/wulkanowy/ui/modules/settings/ads/AdsView.kt
  app/src/play/java/io/github/wulkanowy/utils/AdsHelper.kt
  app/src/play/res/xml/scheme_preferences_ads.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/main/MainPresenterTest.kt
Labels: new feature

#1905 Fix ads tile
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/play/java/io/github/wulkanowy/ui/modules/settings/ads/AdsFragment.kt
  app/src/play/java/io/github/wulkanowy/ui/modules/settings/ads/AdsPresenter.kt
  app/src/play/java/io/github/wulkanowy/utils/AdsHelper.kt
Labels: fix
