Repository wulkanowy/wulkanowy, pull requests merged in 2022-01, with the labels that each got.

#1743 Strip html from school announcements notifications
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewSchoolAnnouncementNotification.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/debug/notification/mock/schoolAnnouncement.kt
Labels: ui, fix

#1744 Differentiate school announcements by userLoginId
  app/src/main/java/io/github/wulkanowy/data/mappers/DirectorInformationMapper.kt
Labels: sync, fix

#1742 Add a custom error message for ssl errors due to invalid clock setting
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardView.kt
  app/src/main/java/io/github/wulkanowy/utils/ExceptionExtension.kt
  app/src/main/java/io/github/wulkanowy/utils/ResourcesExtension.kt
  app/src/main/res/values/strings.xml
Labels: ux

#1767 Add what-the-stack library
  app/build.gradle
Labels: new feature

#1709 Refactor notification destinations
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/48.json
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/Converters.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Notification.kt
  app/src/main/java/io/github/wulkanowy/data/pojos/NotificationData.kt
  app/src/main/java/io/github/wulkanowy/data/serializers/LocalDateSerializer.kt
  app/src/main/java/io/github/wulkanowy/services/shortcuts/ShortcutsHelper.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/AppNotificationManager.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/ChangeTimetableNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewAttendanceNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewConferenceNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewExamNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewGradeNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewHomeworkNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewLuckyNumberNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewMessageNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewNoteNotification.kt
  app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewSchoolAnnouncementNotification.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/Destination.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/debug/notification/mock/timetable.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/notificationscenter/NotificationsCenterAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/notificationscenter/NotificationsCenterFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/notificationscenter/NotificationsCenterPresenter.kt
  app/src/play/java/io/github/wulkanowy/services/messaging/AppMessagingService.kt
Labels: architecture
