Repository wulkanowy/wulkanowy, pull requests merged in 2022-03, with the labels that each got.

#1800 Login improvements
  app/build.gradle
  app/src/main/res/values/api_hosts.xml
  app/src/main/res/values/strings.xml
Labels: ux, app-login

#1801 Add exam date field to exam details dialog
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamDialog.kt
  app/src/main/res/layout/dialog_exam.xml
Labels: enhancement

#1802 Add the option to quickly add a calendar event from the exam details
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamDialog.kt
  app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt
  app/src/main/java/io/github/wulkanowy/utils/IntentUtils.kt
  app/src/main/res/drawable/ic_calendar_all.xml
  app/src/main/res/layout/dialog_additional_add.xml
  app/src/main/res/layout/dialog_exam.xml
  app/src/main/res/layout/dialog_homework_add.xml
  app/src/main/res/values/strings.xml
Labels: new feature

#1780 Add option to select multiple messages to delete
  app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessagePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabDataItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreFragment.kt
  app/src/main/res/drawable/ic_message_select_all.xml
  app/src/main/res/drawable/ic_message_unselect_all.xml
  app/src/main/res/layout/fragment_message_preview.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/menu/action_menu_message_preview.xml
  app/src/main/res/menu/context_menu_attendance.xml
  app/src/main/res/menu/context_menu_message_tab.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: new feature
