Repository wulkanowy/wulkanowy, pull requests merged in 2023-04, with the labels that each got.

#2163 Set error tint to password toggle icon when error occured
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt
  app/src/main/res/layout/fragment_login_form.xml
Labels: enhancement, ux

#2164 Use segmented toggle buttons instead of option group in grades statistics
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsAdapter.kt
  app/src/main/res/layout/item_grade_statistics_header.xml
Labels: ui

#2165 Disable error dialog for admin messages
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
Labels: fix
