Repository wulkanowy/wulkanowy, pull requests merged in 2023-05, with the labels that each got.

#2198 Add auth dialog
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/StudentName.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseDialogFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BasePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseView.kt
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/auth/AuthDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/auth/AuthPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/auth/AuthView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/advanced/AdvancedFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/AppearanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/sync/SyncFragment.kt
  app/src/main/java/io/github/wulkanowy/utils/StudentExtension.kt
  app/src/main/res/drawable/ic_auth_success.xml
  app/src/main/res/layout/dialog_auth.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/play/java/io/github/wulkanowy/ui/modules/settings/ads/AdsFragment.kt
Labels: new feature

#2204 Fix delete user homework button visibility
  app/src/main/res/layout/item_homework_dialog_details.xml
Labels: fix

#2212 Add foojay-resolver and update dependencies
  app/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  settings.gradle
Labels: dependencies

#2217 Add r8 rules for HMS SDK
  app/proguard-rules.pro
Labels: fix

#2220 Add R8 rule for Wulkanowy SDK
  app/proguard-rules.pro
  gradle.properties
Labels: fix
