Repository wulkanowy/wulkanowy, pull requests merged in 2023-10, with the labels that each got.

#2314 Fix student auto selection if there is already active some students logged
  .github/workflows/deploy-store.yml
  .github/workflows/deploy-test.yml
  .github/workflows/test.yml
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt
Labels: bug

#2315 Add negative e-mail validation in school input on support dialog
  app/src/main/java/io/github/wulkanowy/ui/modules/login/support/LoginSupportDialog.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#2317 Add missing class_id colum in JOIN clause of students with semesters
  app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/StudentWithSemesters.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
Labels: db, fix

#2322 Update SDK to 34
  app/build.gradle
  app/jacoco.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/advanced/AdvancedFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/advanced/AdvancedPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/AppearanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/AppearancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/sync/SyncFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/sync/SyncPresenter.kt
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  settings.gradle
Labels: dependencies

#2328 Points statistics improvements
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsAdapter.kt
Labels: enhancement, ui, ux

#2327 Sort teachers by name in school and teachers tab
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/teacher/TeacherPresenter.kt
Labels: enhancement, ux

#2326 Allow direct access to weekend from day navigation when there is any lesson during weekend
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableView.kt
  app/src/main/res/layout/fragment_attendance.xml
  app/src/main/res/layout/fragment_timetable.xml
Labels: enhancement, ux

#2333 Timetable timers fixes
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da-rDK/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-it-rIT/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences_appearance.xml
Labels: fix

#2336 Migrate to separate app-update and review artifacts from play:core
  app/build.gradle
  app/src/fdroid/java/io/github/wulkanowy/utils/InAppUpdateHelper.kt
  app/src/fdroid/java/io/github/wulkanowy/utils/UpdateHelper.kt
  app/src/hms/java/io/github/wulkanowy/utils/InAppUpdateHelper.kt
  app/src/hms/java/io/github/wulkanowy/utils/UpdateHelper.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/play/java/io/github/wulkanowy/utils/InAppUpdateHelper.kt
Labels: fix
