Repository wulkanowy/wulkanowy, pull requests merged in 2023-01, with the labels that each got.

#2090 Fix NPE when trying to remove a message from mailbox that doesn't match any student
  app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
Labels: bug

#2095 Fix school name in dashboard and student details
  app/src/main/res/layout/fragment_account_details.xml
  app/src/main/res/layout/item_dashboard_account.xml
Labels: fix

#2096 Add missing info to student selection email reports
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt
Labels: enhancement, app-login

#2102 Fix marking message as read
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
Labels: ux, fix

#1924 Add menu order settings
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/Destination.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/conference/ConferenceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/conference/ConferencePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/conference/ConferenceView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/HomeworkView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessagePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDeviceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDevicePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/MobileDeviceView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MorePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/more/MoreView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NotePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/note/NoteView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/menuorder/AppMenuItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/menuorder/MenuItemMoveCallback.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/menuorder/MenuOrderAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/menuorder/MenuOrderDividerItemDecoration.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/menuorder/MenuOrderFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/menuorder/MenuOrderItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/menuorder/MenuOrderPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/menuorder/MenuOrderView.kt
  app/src/main/res/drawable/ic_menu_order_drag.xml
  app/src/main/res/layout/fragment_menu_order.xml
  app/src/main/res/layout/item_menu_order.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences_appearance.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/main/MainPresenterTest.kt
Labels: new feature
