Repository wulkanowy/wulkanowy, pull requests merged in 2024-02, with the labels that each got.

#2410 Fix android tests
  .gitignore
  .idea/migrations.xml
  app/build.gradle
  app/src/androidTest/java/io/github/wulkanowy/utils/security/ScramblerTest.kt
Labels: fix

#2412 Add colors to attendance and ! to unexcused lateness
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceDialog.kt
  app/src/main/res/values-night-v31/styles.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values-v31/styles.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#2416 Fix displaying lessons for tomorrow if there is no more lessons for today
  app/src/main/java/io/github/wulkanowy/domain/timetable/IsStudentHasLessonsOnWeekendUseCase.kt
  app/src/main/java/io/github/wulkanowy/domain/timetable/IsWeekendHasLessonsUseCase.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
Labels: fix

#2421 Change default symbol for standard register variant
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginData.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/support/LoginSupportDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolPresenter.kt
  app/src/main/res/values/api_hosts.xml
  app/src/test/java/io/github/wulkanowy/TestEnityCreator.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
Labels: hotfix, uonet-update

#2425 Add missing symbol and custom domain suffix validation
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolPresenter.kt
  app/src/main/res/layout/fragment_login_form.xml
  app/src/main/res/values/strings.xml
Labels: ux

#2427 Make WebkitCookieManagerProxy no-op if webview is not available on the device
  app/src/main/java/io/github/wulkanowy/utils/WebkitCookieManagerProxy.kt
Labels: hotfix

#2430 Fix error handling in widgets
  app/src/main/java/io/github/wulkanowy/data/Resource.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetItem.kt
  app/src/main/res/layout/item_widget_timetable_error.xml
  app/src/main/res/layout/widget_timetable.xml
Labels: fix

#2433 Fix text pasting into date field in additional lesson add dialog
  app/src/main/res/layout/dialog_additional_add.xml
Labels: fix

#2434 Revert "Bump com.google.android.ump:user-messaging-platform from 2.1.0 to 2.2.0"
  app/build.gradle
Labels: hotfix

#2435 Fix text cut off across the app when text size is set to 200%
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_account_edit.xml
  app/src/main/res/layout/dialog_additional_add.xml
  app/src/main/res/layout/dialog_attendance.xml
  app/src/main/res/layout/dialog_conference.xml
  app/src/main/res/layout/dialog_exam.xml
  app/src/main/res/layout/dialog_grade.xml
  app/src/main/res/layout/dialog_homework.xml
  app/src/main/res/layout/dialog_homework_add.xml
  app/src/main/res/layout/dialog_lesson_completed.xml
  app/src/main/res/layout/dialog_mobile_device.xml
  app/src/main/res/layout/dialog_note.xml
  app/src/main/res/layout/dialog_school_announcement.xml
  app/src/main/res/layout/dialog_timetable.xml
  app/src/main/res/layout/header_grade_details.xml
  app/src/main/res/layout/item_timetable.xml
  app/src/main/res/layout/subitem_dashboard_small_grade.xml
Labels: ui, fix

#2436 Fix loading timetable and attendance when should be refreshed returns true
  app/src/main/java/io/github/wulkanowy/data/db/dao/TimetableDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/TimetableRepository.kt
  app/src/main/java/io/github/wulkanowy/domain/timetable/IsStudentHasLessonsOnWeekendUseCase.kt
  app/src/main/java/io/github/wulkanowy/services/sync/works/TimetableWork.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
Labels: ux, fix

#2437 Fix error handling in login
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/auth/AuthPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/ExceptionExtension.kt
  app/src/main/res/values/api_hosts.xml
  app/src/main/res/values/strings.xml
Labels: fix
