Repository wulkanowy/wulkanowy, pull requests merged in 2024-01, with the labels that each got.

#2375 Add User Messaging Platform SDK for ads agreements
  app/build.gradle
  app/src/fdroid/java/io/github/wulkanowy/utils/AdsHelper.kt
  app/src/hms/java/io/github/wulkanowy/utils/AdsHelper.kt
  app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainView.kt
  app/src/main/res/layout/dialog_ads_consent.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da-rDK/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-it-rIT/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/strings.xml
  app/src/play/java/io/github/wulkanowy/ui/modules/settings/ads/AdsFragment.kt
  app/src/play/java/io/github/wulkanowy/ui/modules/settings/ads/AdsPresenter.kt
  app/src/play/java/io/github/wulkanowy/ui/modules/settings/ads/AdsView.kt
  app/src/play/java/io/github/wulkanowy/utils/AdsHelper.kt
  app/src/play/java/io/github/wulkanowy/utils/AnalyticsHelper.kt
  app/src/play/res/xml/scheme_preferences_ads.xml
Labels: new feature

#2385 Update AGP and Gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies

#2387 Update slf4j-timber
  app/build.gradle
Labels: dependencies

#2386 Add clearing all data and key entry when decryption failed
  app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseDialogFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BasePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseView.kt
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/advanced/AdvancedFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/AppearanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/sync/SyncFragment.kt
  app/src/main/java/io/github/wulkanowy/utils/security/Scrambler.kt
  app/src/main/res/values/strings.xml
  app/src/play/java/io/github/wulkanowy/ui/modules/settings/ads/AdsFragment.kt
Labels: ux, new feature

#2390 Use emptyCookieJarInterceptor in SDK configuration
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/utils/SdkExtension.kt
Labels: enhancement

#2391 Avoid deleting luckynumber when SDK returns null
  app/src/main/java/io/github/wulkanowy/data/repositories/LuckyNumberRepository.kt
Labels: fix

#2393 Make some improvements in captcha dialog
  app/src/main/java/io/github/wulkanowy/services/alarm/TimetableNotificationSchedulerHelper.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseDialogFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/base/BaseFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/captcha/CaptchaDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/debug/DebugFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/debug/DebugPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/debug/DebugView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/advanced/AdvancedFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/AppearanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/sync/SyncFragment.kt
  app/src/main/java/io/github/wulkanowy/utils/ExceptionExtension.kt
  app/src/main/java/io/github/wulkanowy/utils/WebkitCookieManagerProxy.kt
  app/src/main/res/layout/dialog_captcha.xml
  app/src/main/res/values/strings.xml
Labels: ux

#2395 Fix cancelling dashboard jobs
  app/src/main/java/io/github/wulkanowy/data/Resource.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/captcha/CaptchaDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
Labels: fix

#2396 New Crowdin updates
  app/src/main/res/values-da-rDK/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-it-rIT/strings.xml
  app/src/main/res/values-ru/strings.xml
Labels: translation

#2401 Add X to close admin message
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/58.json
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/AdminMessage.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration58.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/viewholders/AdminMessageViewHolder.kt
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/layout/item_dashboard_admin_message.xml
Labels: ux, new feature
