Repository wulkanowy/wulkanowy, pull requests merged in 2024-03, with the labels that each got.

#2446 Fix timetable items layout
  app/src/main/res/layout/item_timetable.xml
  app/src/main/res/layout/subitem_dashboard_small_grade.xml
Labels: ui, fix

#2438 Add message from trash restoring
  app/src/main/java/io/github/wulkanowy/data/enums/MessageFolder.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessagePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
  app/src/main/res/drawable/ic_menu_message_delete_forever.xml
  app/src/main/res/drawable/ic_menu_message_restore.xml
  app/src/main/res/menu/action_menu_message_preview.xml
  app/src/main/res/menu/context_menu_message_tab.xml
  app/src/main/res/values/strings.xml
Labels: new feature

#2452 Add last announcements to school announcements
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/61.json
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/SchoolAnnouncement.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/DirectorInformationMapper.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SchoolAnnouncementRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementAdapter.kt
  app/src/main/res/layout/item_school_announcement.xml
Labels: db, new feature

#2448 Fix calculating average with optional arithmetic average on and no grade with average in second semester
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProvider.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
Labels: fix

#2451 Improve invalid password message
  app/src/main/java/io/github/wulkanowy/ui/base/BaseActivity.kt
  app/src/main/java/io/github/wulkanowy/utils/ExceptionExtension.kt
  app/src/main/res/values/strings.xml
Labels: ux

#2450 Wrap delete and save operations in database transactions
  app/src/main/java/io/github/wulkanowy/data/db/dao/AdminMessageDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/BaseDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceSummaryRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/CompletedLessonsRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/ConferenceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/ExamRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/GradeRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/GradeStatisticsRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/HomeworkRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/LuckyNumberRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/MobileDeviceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/NoteRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/RecipientRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SchoolAnnouncementRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SchoolRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SemesterRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentInfoRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SubjectRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/TeacherRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/TimetableRepository.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/AttendanceRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/CompletedLessonsRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/ExamRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/GradeRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/GradeStatisticsRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/LuckyNumberRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/MessageRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/MobileDeviceRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/RecipientLocalTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/SemesterRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/TimetableRepositoryTest.kt
Labels: db

#2459 Add a message explaining the reason for the captcha to the captcha dialog
  app/src/main/java/io/github/wulkanowy/data/DataModule.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/captcha/CaptchaDialog.kt
  app/src/main/java/io/github/wulkanowy/utils/WebkitCookieManagerProxy.kt
  app/src/main/res/layout/dialog_captcha.xml
  app/src/main/res/values/strings.xml
Labels: ux

#1597 Add attendance calculator
  app/src/main/java/io/github/wulkanowy/data/Resource.kt
  app/src/main/java/io/github/wulkanowy/data/enums/AttendanceCalculatorSortingMode.kt
  app/src/main/java/io/github/wulkanowy/data/pojos/AttendanceData.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceSummaryRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
  app/src/main/java/io/github/wulkanowy/domain/attendance/GetAttendanceCalculatorDataUseCase.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/calculator/AttendanceCalculatorAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/calculator/AttendanceCalculatorFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/calculator/AttendanceCalculatorPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/calculator/AttendanceCalculatorView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/AppearanceFragment.kt
  app/src/main/java/io/github/wulkanowy/utils/AttendanceExtension.kt
  app/src/main/res/drawable/ic_menu_attendance_calculator.xml
  app/src/main/res/layout/fragment_attendance_calculator.xml
  app/src/main/res/layout/item_attendance_calculator_header.xml
  app/src/main/res/layout/pref_target_attendance.xml
  app/src/main/res/menu/action_menu_attendance.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values/preferences_defaults.xml
  app/src/main/res/values/preferences_keys.xml
  app/src/main/res/values/preferences_values.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/scheme_preferences_appearance.xml
Labels: new feature

#2468 Update gradle to 8.6
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#2475 Fix task description color crash
  .gitignore
  app/src/main/java/io/github/wulkanowy/ui/base/BaseActivity.kt
Labels: fix

#2476 Add missing onDetachView in AutDialog
  app/src/main/java/io/github/wulkanowy/ui/modules/auth/AuthDialog.kt
Labels: fix

#2477 Remove savedInstance in MessagePreviewFragment
  app/src/main/java/io/github/wulkanowy/ui/modules/message/mailboxchooser/MailboxChooserDialog.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/BundleExtension.kt
Labels: fix

#2481 Fix lateness color in attendance
  app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceAdapter.kt
  app/src/main/res/values/colors.xml
Labels: ui, fix

#2479 Add WulkanowySdkFactory
  app/src/main/java/io/github/wulkanowy/data/DataModule.kt
  app/src/main/java/io/github/wulkanowy/data/WulkanowySdkFactory.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceSummaryRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/CompletedLessonsRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/ConferenceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/ExamRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/GradeRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/GradeStatisticsRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/HomeworkRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/LuckyNumberRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/MobileDeviceRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/NoteRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/RecipientRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/RecoverRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SchoolAnnouncementRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SchoolRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SchoolsRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SemesterRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentInfoRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SubjectRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/TeacherRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/TimetableRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/captcha/CaptchaDialog.kt
  app/src/main/java/io/github/wulkanowy/utils/SdkExtension.kt
  app/src/test/java/io/github/wulkanowy/WulkanowySdkFactoryCreator.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/AttendanceRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/CompletedLessonsRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/ExamRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/GradeRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/GradeStatisticsRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/LuckyNumberRemoteTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/MessageRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/MobileDeviceRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/RecipientLocalTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/SemesterRepositoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/TimetableRepositoryTest.kt
Labels: enhancement

#2495 Change AuthDialog condition to isAuth flag
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/62.json
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Student.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/StudentIsAuthorized.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/RegisterUserMapper.kt
  app/src/main/java/io/github/wulkanowy/data/pojos/RegisterUser.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/base/ErrorHandler.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/utils/SdkExtension.kt
  app/src/test/java/io/github/wulkanowy/TestEnityCreator.kt
  app/src/test/java/io/github/wulkanowy/domain/GetMailboxByStudentUseCaseTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
  app/src/test/java/io/github/wulkanowy/ui/modules/main/MainPresenterTest.kt
Labels: fix

#2497 Add try catch to initialize MobileAds SDK
  app/src/play/java/io/github/wulkanowy/utils/AdsHelper.kt
Labels: fix

#2498 Hide lesson number when is eduOne
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetItem.kt
Labels: bug

#2499 Add isAdded condition to HomeworkAddDialog
  app/src/main/java/io/github/wulkanowy/ui/modules/homework/add/HomeworkAddDialog.kt
Labels: fix

#2500 Add ignoring FeatureUnavailableException in SyncWorker
  app/src/main/java/io/github/wulkanowy/services/sync/SyncWorker.kt
Labels: fix

#2496 Hide grade statistics when is eduOne
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/63.json
  app/src/main/java/io/github/wulkanowy/data/WulkanowySdkFactory.kt
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/Student.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/StudentIsAuthorized.kt
  app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration63.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeView.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
  app/src/main/java/io/github/wulkanowy/utils/SdkExtension.kt
  app/src/test/java/io/github/wulkanowy/WulkanowySdkFactoryCreator.kt
  app/src/test/java/io/github/wulkanowy/data/WulkanowySdkFactoryTest.kt
  app/src/test/java/io/github/wulkanowy/data/db/migrations/AbstractMigrationTest.kt
  app/src/test/java/io/github/wulkanowy/data/db/migrations/Migration54Test.kt
  app/src/test/java/io/github/wulkanowy/data/db/migrations/Migration63Test.kt
Labels: fix

#2501 Fix issues related to not authenticated eduOne students
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/auth/AuthPresenter.kt
Labels: fix

#2507 Add logging error from units and symbols
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
  app/src/main/java/io/github/wulkanowy/utils/SemesterExtension.kt
Labels: enhancement

#2509 Remove classId from semester query when eduOne
  app/build.gradle
  app/src/main/java/io/github/wulkanowy/data/db/dao/SemesterDao.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SemesterRepository.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
  app/src/test/java/io/github/wulkanowy/data/repositories/SemesterRepositoryTest.kt
Labels: fix

#2508 Add skipping migration when previous attempt failed
  app/src/main/java/io/github/wulkanowy/data/WulkanowySdkFactory.kt
  app/src/main/java/io/github/wulkanowy/data/repositories/SemesterRepository.kt
Labels: fix
