Repository wulkanowy/wulkanowy, pull requests merged in 2024-04, with the labels that each got.

#2515 Add isAdded check in AdditionalLessonAddDialog
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/add/AdditionalLessonAddDialog.kt
Labels: fix

#2506 Update AuthDialog text
  app/src/main/java/io/github/wulkanowy/ui/modules/auth/AuthPresenter.kt
  app/src/main/res/layout/dialog_auth.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#2524 Display separate annual average and semester average if available
  app/build.gradle
  app/schemas/io.github.wulkanowy.data.db.AppDatabase/64.json
  app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
  app/src/main/java/io/github/wulkanowy/data/db/entities/GradeSummary.kt
  app/src/main/java/io/github/wulkanowy/data/mappers/GradeMapper.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/debug/notification/mock/gradeSummary.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProvider.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsItem.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryAdapter.kt
  app/src/main/res/layout/header_grade_details.xml
  app/src/main/res/layout/item_grade_summary.xml
  app/src/main/res/layout/scrollable_header_grade_summary.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
  app/src/test/java/io/github/wulkanowy/utils/GradeExtensionTest.kt
Labels: db, ux, uonet-update

#2486 Fix race condition of showing empty view in timetable
  app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/history/LuckyNumberHistoryAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
  app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableView.kt
  app/src/main/java/io/github/wulkanowy/utils/SyncListAdapter.kt
Labels: fix
